/**
 * `luaudocs init`: the scaffolded file set, placeholder substitution, re-run
 * semantics, and the one-time moonwave conversion, all through the public
 * `initProject` entry.
 */
import { execFileSync } from "node:child_process";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, relative } from "node:path";
import { beforeAll, describe, expect, it, vi } from "vitest";
import toolPkg from "../package.json";
import { loadConfig } from "../src/config";
import { packageRoot } from "../src/extract";
import { initProject } from "../src/init";
import { filesUnder, fixturePath, makeTempDirFactory } from "./helpers";

const tempDir = makeTempDirFactory("luaudocs-scaffold-");

/** The shape of an init substitution token; none may survive into a project.
 * The shape rather than the current vocabulary, so a token added to the
 * templates later is covered without this list knowing about it. */
const PLACEHOLDER = /@[A-Z_]+@/;

/** The text scans below decode what they read; the packaged font would come
 * back as replacement characters and match on whatever those happen to spell. */
const BINARY = /\.woff2$/;

// init reports every file it writes, on every call the suite makes
beforeAll(() => {
	vi.spyOn(console, "log").mockImplementation(() => {});
});

/** `initProject` with its console.log lines captured (the conversion report). */
async function initCapturing(options: Parameters<typeof initProject>[0]): Promise<string[]> {
	const lines: string[] = [];
	const spy = vi
		.spyOn(console, "log")
		.mockImplementation((...args: unknown[]) => void lines.push(args.join(" ")));
	try {
		await initProject(options);
	} finally {
		spy.mockRestore();
		// the beforeAll silencer again, for whatever runs next
		vi.spyOn(console, "log").mockImplementation(() => {});
	}
	return lines;
}

describe("init", () => {
	// the tests below are views of one scaffold, so they share it. Every test
	// that mutates its project keeps a dir of its own.
	let dir: string;
	let docsDir: string;
	beforeAll(async () => {
		dir = tempDir();
		docsDir = join(dir, ".luaudocs");
		await initProject({ targetDir: dir, title: "MyLib", description: "Does things" });
	});

	it("writes a config the loader accepts, with init's values in it", () => {
		const loaded = loadConfig(dir);
		expect(loaded.config.title).toBe("MyLib");
		expect(loaded.config.description).toBe("Does things");
		expect(loaded.config.docs.dir).toBe(".luaudocs");
		// no git remote in a temp dir, so [repo] stays commented out
		expect(loaded.config.repo).toBeUndefined();
		expect(readFileSync(join(dir, "luaudocs.toml"), "utf8")).toContain('# dir = ".luaudocs"');
	});

	it("scaffolds the user-owned content", () => {
		expect(readFileSync(join(docsDir, "index.md"), "utf8")).toContain('name: "MyLib"');
		expect(existsSync(join(docsDir, "custom.css"))).toBe(true);
		expect(existsSync(join(docsDir, "public"))).toBe(true);

		// the scaffolded guide sits where the sidebar walk reads it, and the
		// hero button on the landing page points at that link
		const guide = join(docsDir, "guide", "getting-started.md");
		expect(readFileSync(guide, "utf8")).toContain("Welcome to the **MyLib** documentation.");
		expect(readFileSync(join(docsDir, "index.md"), "utf8")).toContain(
			"link: /guide/getting-started",
		);
	});

	// the template ships dotless (npm strips .gitignore from tarballs), so init
	// must put the dot back or every regenerated tree lands in git history
	it("scaffolds the site .gitignore from the dotless template", () => {
		const ignore = readFileSync(join(docsDir, ".gitignore"), "utf8");
		for (const line of [
			".vitepress/",
			"api/",
			"changelog.md",
			"package.json",
			"node_modules/",
		]) {
			expect(ignore, line).toContain(line);
		}
	});

	it("syncs the .vitepress machinery so the site resolves before the first build", () => {
		const config = readFileSync(join(docsDir, ".vitepress", "config.mts"), "utf8");
		expect(config).toContain("Generated by luaudocs");
		expect(config).toContain('title: "MyLib"');
		expect(config).toContain('from "./generated/sidebar.ts"');

		// the icon plugin is wired at both ends: the md/vite halves in the
		// config, the stylesheet they mint in the theme entry
		expect(config).toContain('from "vitepress-plugin-group-icons"');
		expect(config).toContain("md.use(groupIconMdPlugin);");
		expect(config).toContain("groupIconVitePlugin({ customIcon: codeIcons })");
		expect(config).toContain('from "./generated/icons.ts"');

		// custom.css was scaffolded, so the theme entry wires it in
		const theme = readFileSync(join(docsDir, ".vitepress", "theme", "index.ts"), "utf8");
		expect(theme).toContain('import "virtual:group-icons.css"');
		expect(theme).toContain('import "../generated/luaudocs.css"');
		expect(theme).toContain('import "../../custom.css"');

		for (const name of [
			"markup.ts",
			"icons.ts",
			"inline-highlight.ts",
			"search-cache.ts",
			"signature-links.ts",
			"luaudocs.css",
			"sidebar.ts",
			"trails.ts",
			"FiraCode-VF.woff2",
			"FiraCode-OFL.txt",
		]) {
			expect(existsSync(join(docsDir, ".vitepress", "generated", name)), name).toBe(true);
		}

		// the install anchors on a generated package.json whose ranges come
		// from the tool's own, so the runtime and vitepress cannot drift
		const pkg = JSON.parse(readFileSync(join(docsDir, "package.json"), "utf8")) as {
			private: boolean;
			devDependencies: Record<string, string>;
		};
		expect(pkg.private).toBe(true);
		expect(pkg.devDependencies.vitepress).toBe(toolPkg.devDependencies.vitepress);
		expect(pkg.devDependencies.vue).toBe(toolPkg.devDependencies.vue);
		expect(pkg.devDependencies["vitepress-plugin-group-icons"]).toBe(
			toolPkg.devDependencies["vitepress-plugin-group-icons"],
		);
	});

	// synced as text, the font still arrives at the right path and a plausible
	// size with every undecodable byte replaced: the browser silently falls back
	// to the next family, so nothing fails except this comparison
	it("copies the packaged font byte for byte", () => {
		const source = join(packageRoot(), "templates", "runtime", "FiraCode-VF.woff2");
		const synced = join(docsDir, ".vitepress", "generated", "FiraCode-VF.woff2");
		const bytes = readFileSync(synced);

		expect(bytes.equals(readFileSync(source))).toBe(true);
		// the woff2 signature, so a passing comparison of two corrupt copies
		// cannot be what makes this green
		expect(bytes.subarray(0, 4).toString("latin1")).toBe("wOF2");
	});

	// the @font-face resolves relative to the stylesheet, so the two travel
	// together or vite fails the build with an unresolved asset
	it("points the stylesheet at the font beside it", () => {
		const css = readFileSync(join(docsDir, ".vitepress", "generated", "luaudocs.css"), "utf8");

		expect(css).toContain('src: url("./FiraCode-VF.woff2")');
		expect(css).toContain("--vp-font-family-mono:");
	});

	it("resolves every placeholder it scaffolds", () => {
		const files = filesUnder(dir);
		// an empty scan would pass vacuously with the scaffold itself broken
		expect(files.length).toBeGreaterThan(0);
		const offenders = files
			.filter((file) => !BINARY.test(file) && PLACEHOLDER.test(readFileSync(file, "utf8")))
			.map((file) => relative(dir, file));

		expect(offenders).toEqual([]);
	});

	// a formatter run over the templates rewrites `__x__` to `**x**`, silently
	// destroying the placeholder for every project scaffolded afterwards
	it("keeps packaged placeholders in a form markdown formatters cannot rewrite", () => {
		const root = join(packageRoot(), "templates");
		const files = filesUnder(root);
		expect(files.length).toBeGreaterThan(0);
		const offenders = files
			.filter(
				(file) => !BINARY.test(file) && /__[A-Za-z0-9]+__/.test(readFileSync(file, "utf8")),
			)
			.map((file) => relative(root, file));

		expect(offenders).toEqual([]);
	});

	// npm-packlist drops these basenames from every tarball regardless of the
	// "files" field, so a template carrying one scaffolds fine from a repo
	// checkout but vanishes for npm consumers
	it("never packages a template under a name npm strips from tarballs", () => {
		const STRIPPED = new Set([
			".gitignore",
			".npmignore",
			".npmrc",
			".DS_Store",
			"node_modules",
			"package-lock.json",
			"yarn.lock",
			"pnpm-lock.yaml",
		]);
		const root = join(packageRoot(), "templates");
		const files = filesUnder(root);
		expect(files.length).toBeGreaterThan(0);
		const offenders = files
			.filter((file) => STRIPPED.has(basename(file)))
			.map((file) => relative(root, file));

		expect(offenders).toEqual([]);
	});

	// tokens inside .md frontmatter sit in quoted YAML scalars, so a quote in
	// the title must arrive escaped there and raw in prose
	it("escapes substituted frontmatter values but not prose", async () => {
		const quotedDir = tempDir();
		await initProject({ targetDir: quotedDir, title: 'My "Quoted" Lib' });

		const index = readFileSync(join(quotedDir, ".luaudocs", "index.md"), "utf8");
		expect(index).toContain('name: "My \\"Quoted\\" Lib"');
		const guide = readFileSync(
			join(quotedDir, ".luaudocs", "guide", "getting-started.md"),
			"utf8",
		);
		expect(guide).toContain('Welcome to the **My "Quoted" Lib** documentation.');
	});

	it("enables [repo] when a GitHub remote exists", async () => {
		const repoDir = tempDir();
		execFileSync("git", ["init"], { cwd: repoDir });
		execFileSync("git", ["remote", "add", "origin", "git@github.com:user/mylib.git"], {
			cwd: repoDir,
		});
		await initProject({ targetDir: repoDir, title: "MyLib" });

		expect(loadConfig(repoDir).config.repo?.url).toBe("https://github.com/user/mylib");
		// and the baked site config carries the edit link it enables
		const config = readFileSync(join(repoDir, ".luaudocs", ".vitepress", "config.mts"), "utf8");
		expect(config).toContain("https://github.com/user/mylib");
		expect(config).toContain("Edit this page on GitHub");
	});

	it("re-running skips user files but refreshes the generated machinery", async () => {
		const rerunDir = tempDir();
		await initProject({ targetDir: rerunDir, title: "MyLib" });
		const cssPath = join(rerunDir, ".luaudocs", "custom.css");
		writeFileSync(cssPath, "/* user edited */\n");
		// the machinery is generated: a stale copy is refreshed, never preserved
		const shimPath = join(rerunDir, ".luaudocs", ".vitepress", "config.mts");
		writeFileSync(shimPath, "// stale\n");

		await initProject({ targetDir: rerunDir, title: "MyLib" });
		expect(readFileSync(cssPath, "utf8")).toBe("/* user edited */\n");
		expect(readFileSync(shimPath, "utf8")).toContain("defineConfig");
	});

	// a config-less build supplies a marked index.md and .gitignore; init must
	// swap those for the editable templates, or "skipped (exists)" leaves the
	// scaffolded landing page gitignored and the hero unreachable
	it("replaces marker-carrying generated files with the editable templates", async () => {
		const genDir = tempDir();
		const genDocs = join(genDir, ".luaudocs");
		writeFileSync(join(genDir, "luaudocs.toml"), 'title = "MyLib"\n');
		mkdirSync(genDocs, { recursive: true });
		writeFileSync(
			join(genDocs, "index.md"),
			"---\n# Generated by luaudocs; rewritten by every build.\nlayout: home\n---\n",
		);
		writeFileSync(
			join(genDocs, ".gitignore"),
			"# Generated by luaudocs; created because it was missing.\napi/\nindex.md\n",
		);

		await initProject({ targetDir: genDir, title: "MyLib" });
		expect(readFileSync(join(genDocs, "index.md"), "utf8")).toContain('name: "MyLib"');
		const ignore = readFileSync(join(genDocs, ".gitignore"), "utf8");
		expect(ignore).not.toContain("Generated by luaudocs");
		expect(ignore).toContain(".vitepress/");
		// the template does not ignore the landing page init just scaffolded
		expect(ignore).not.toMatch(/^index\.md$/m);
	});
});

describe("init --force", () => {
	// --force re-templates luaudocs.toml. Without carrying the existing dir
	// across, the config reverts to the default while every scaffolded file
	// stays put, and the next build generates an empty site beside them.
	it("keeps a custom [docs] dir when it re-templates the config", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "luaudocs.toml"), 'title = "Custom"\n\n[docs]\ndir = "mydocs"\n');
		await initProject({ targetDir: dir });
		await initProject({ targetDir: dir, force: true });

		const loaded = loadConfig(dir);
		expect(loaded.config.docs.dir).toBe("mydocs");
		expect(existsSync(join(dir, "mydocs", "index.md"))).toBe(true);
		expect(existsSync(join(dir, ".luaudocs"))).toBe(false);
		// and the baked config agrees, so the edit-link pattern would resolve
		expect(existsSync(join(dir, "mydocs", ".vitepress", "config.mts"))).toBe(true);
	});
});

describe("init --from-moonwave", () => {
	it("converts moonwave-full.toml, mapping what has an equivalent", async () => {
		const dir = tempDir();
		copyFileSync(fixturePath("moonwave-full.toml"), join(dir, "moonwave.toml"));
		const lines = await initCapturing({ targetDir: dir, fromMoonwave: true });

		const converted = readFileSync(join(dir, "luaudocs.toml"), "utf8");
		await expect(converted).toMatchFileSnapshot("__snapshots__/moonwave-full-luaudocs.toml");

		// the snapshot pins the full text; these rows keep a blind `vitest -u`
		// from silently dropping a mapping
		for (const marker of [
			'title = "Brume"',
			'description = "An invented library for exercising the converter."',
			'entries = [ "src" ]',
			'url = "https://github.com/brume-labs/brume"',
			'branch = "trunk"',
			"changelog = false",
			"includeReadme = true",
			// docusaurus url + baseUrl joined into one published URL
			'url = "https://brume-labs.github.io/brume/"',
			'siteTitle = "BrumeNav"',
			// static-dir paths arrive rooted for public/
			'favicon = "/icon.svg"',
			'light = "/logo-light.svg"',
			'dark = "/logo-dark.svg"',
			'copyright = "© Brume Labs"',
		]) {
			expect(converted).toContain(marker);
		}

		// the derived entries are baked ahead of the custom item: the Guide
		// entry aims at the scaffolded sample guide (the fixture project has
		// no docs/), and changelog = false keeps the Changelog entry out
		const loaded = loadConfig(dir);
		expect(loaded.config.site.nav).toEqual([
			{ text: "Guide", link: "/guide/getting-started", activeMatch: "^/guide/" },
			{ text: "API", link: "/api/", activeMatch: "^/api/" },
			{ text: "Discord", link: "https://discord.gg/brume" },
		]);

		// nav-shaped moonwave keys have no equivalent: the generated nav follows
		// the public access graph, so nothing in the output may respell them
		expect(converted).not.toContain("classOrder");
		expect(converted).not.toContain("apiCategories");
		expect(converted).not.toContain("navbar");

		// the homepage branding becomes a real, user-owned home-layout page
		// (the fixture's features list is empty, so the hero stands alone, and
		// its includeReadme finds no README to include)
		const index = readFileSync(join(dir, ".luaudocs", "index.md"), "utf8");
		expect(index).toContain("layout: home");
		expect(index).toContain('image: "/banner.svg"');
		expect(index).not.toContain("Generated by luaudocs");
		expect(index).not.toContain("@include");

		// and the conversion says so, naming every unmapped key the fixture
		// carries and nothing it mapped
		const report = lines.join("\n");
		expect(report).toContain("no equivalent:");
		for (const named of [
			"classOrder",
			"apiCategories",
			"autoSectionPath",
			"navbar.hideOnScroll",
			"footer.links",
		]) {
			expect(report).toContain(named);
		}
		expect(report).not.toContain("gitRepoUrl");
		expect(report).not.toContain("home.bannerImage");
		expect(report).not.toContain("home.features");
		expect(report).toContain("note: [[site.nav]] replaces the derived navbar");

		// the moot keys are consumed silently: absent from the report and the
		// output alike (convertMoonwave's doc says why each is moot)
		for (const silent of [
			"deploymentBranch",
			"onBrokenLinks",
			"onBrokenMarkdownLinks",
			"trailingSlash",
			"footer.style",
			"organizationName",
			"projectName",
			"home.enabled",
		]) {
			expect(report, silent).not.toContain(silent);
			expect(converted, silent).not.toContain(silent);
		}

		// the converted config drives the loader like any hand-written one
		expect(loaded.config.title).toBe("Brume");
		expect(loaded.config.repo).toEqual({
			url: "https://github.com/brume-labs/brume",
			branch: "trunk",
		});
		// validation trims the trailing slash the conversion carried
		expect(loaded.config.docs.url).toBe("https://brume-labs.github.io/brume");
		expect(loaded.config.site.siteTitle).toBe("BrumeNav");
		expect(loaded.config.site.favicon).toBe("/icon.svg");
		expect(loaded.config.site.logo).toEqual({
			light: "/logo-light.svg",
			dark: "/logo-dark.svg",
		});
		expect(loaded.config.site.footer).toEqual({ copyright: "© Brume Labs" });
	});

	// the deploy coordinates name the same GitHub repo and pages host moonwave
	// itself derives, so with gitRepoUrl and docusaurus.url absent they are the
	// fallbacks rather than dead keys
	it("derives [repo] and [docs] url from organizationName/projectName", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			[
				'title = "X"',
				"",
				"[docusaurus]",
				'organizationName = "brume-labs"',
				'projectName = "brume"',
				'baseUrl = "/brume/"',
			].join("\n"),
		);
		const lines = await initCapturing({ targetDir: dir, fromMoonwave: true });

		const loaded = loadConfig(dir);
		expect(loaded.config.repo).toEqual({
			url: "https://github.com/brume-labs/brume",
			branch: "main",
		});
		expect(loaded.config.docs.url).toBe("https://brume-labs.github.io/brume");
		expect(lines.join("\n")).not.toContain("no equivalent");
		// no custom navbar.items, so nothing was baked and nothing is noted
		expect(lines.join("\n")).not.toContain("note:");
	});

	// with baseUrl unset, moonwave's own project-pages default applies: the
	// site serves from /<project>/, and a bare host would ship a broken base
	it("defaults the derived [docs] url base to the project name", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			[
				'title = "X"',
				"",
				"[docusaurus]",
				'organizationName = "brume-labs"',
				'projectName = "brume"',
			].join("\n"),
		);
		await initCapturing({ targetDir: dir, fromMoonwave: true });
		expect(loadConfig(dir).config.docs.url).toBe("https://brume-labs.github.io/brume");
	});

	// junk deploy coordinates drop the derived url rather than abort init
	it("survives an organizationName that cannot form a URL", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			['title = "X"', "", "[docusaurus]", 'organizationName = "my org"'].join("\n"),
		);
		await initCapturing({ targetDir: dir, fromMoonwave: true });
		expect(loadConfig(dir).config.docs.url).toBeUndefined();
	});

	// a malformed config aborts before any conversion output lands, so a fix
	// and re-run start from a clean tree
	it("writes nothing when the moonwave config does not parse", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "moonwave.toml"), 'title = "X\n');
		mkdirSync(join(dir, "docs"), { recursive: true });
		writeFileSync(join(dir, "docs", "intro.md"), "# Intro\n");
		await expect(initProject({ targetDir: dir, fromMoonwave: true })).rejects.toThrow();
		expect(existsSync(join(dir, ".luaudocs"))).toBe(false);
		expect(existsSync(join(dir, "luaudocs.toml"))).toBe(false);
	});

	// the full fixture exercises the carry direction (changelog = false,
	// includeReadme = true); this pins the drop direction: default-equivalent
	// values are neither copied into the output nor reported as unmapped
	it("drops changelog = true and includeReadme = false as defaults", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			['title = "X"', "changelog = true", "", "[home]", "includeReadme = false"].join("\n"),
		);
		const lines = await initCapturing({ targetDir: dir, fromMoonwave: true });

		const converted = readFileSync(join(dir, "luaudocs.toml"), "utf8");
		expect(converted).not.toContain("changelog");
		expect(converted).not.toContain("includeReadme");
		expect(lines.join("\n")).not.toContain("no equivalent");
	});

	it("says nothing when there is nothing it cannot carry", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			['title = "X"', 'gitRepoUrl = "https://example.test/x"'].join("\n"),
		);
		const lines = await initCapturing({ targetDir: dir, fromMoonwave: true });
		expect(lines.join("\n")).not.toContain("no equivalent");
	});

	// the converted config never carries a [docs] dir of its own (moonwave has
	// no equivalent), so an existing custom dir must be carried over or the
	// content and the config split across two directories
	it("keeps a custom [docs] dir through --force conversion", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "moonwave.toml"), 'title = "Converted"\n');
		writeFileSync(join(dir, "luaudocs.toml"), 'title = "Old"\n\n[docs]\ndir = "docs"\n');

		await initProject({ targetDir: dir, force: true, fromMoonwave: true });

		const loaded = loadConfig(dir);
		expect(loaded.config.title).toBe("Converted");
		expect(loaded.config.docs.dir).toBe("docs");
		expect(existsSync(join(dir, "docs", "index.md"))).toBe(true);
		expect(existsSync(join(dir, "docs", ".vitepress", "config.mts"))).toBe(true);
		expect(existsSync(join(dir, ".luaudocs"))).toBe(false);
	});

	it("converts the hand-written docs/ and pages/ folders", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			[
				'title = "X"',
				"",
				"[[navbar.items]]",
				'href = "https://example.test/chat"',
				'label = "Chat"',
				"",
				"[[navbar.items]]",
				'label = "Setup"',
				'to = "docs/tutorial/setup"',
			].join("\n"),
		);
		mkdirSync(join(dir, "docs", "tutorial"), { recursive: true });
		writeFileSync(
			join(dir, "docs", "intro.md"),
			[
				"---",
				"sidebar_position: 1",
				"---",
				"",
				'import Tabs from "@theme/Tabs";',
				'import TabItem from "@theme/TabItem";',
				"",
				"# Intro",
				"",
				"{/* draft */}",
				"",
				"See [setup](/docs/tutorial/setup) and [the API](/api/).",
				"",
				'```lua title="init.lua" showLineNumbers',
				'print("hi")',
				"```",
				"",
			].join("\n"),
		);
		writeFileSync(
			join(dir, "docs", "tutorial", "_category_.json"),
			'{ "label": "Tutorial", "position": 2, "className": "tutorial" }\n',
		);
		writeFileSync(
			join(dir, "docs", "tutorial", "setup.mdx"),
			[
				"---",
				"slug: /setup-anywhere",
				"---",
				"",
				"# Setup",
				"",
				"<TOCInline toc={toc} />",
				"",
				"Back to [intro](../intro.mdx).",
				"",
			].join("\n"),
		);
		writeFileSync(join(dir, "docs", "wip.md"), "---\ndraft: true\n---\n\n# WIP\n");
		writeFileSync(
			join(dir, "docs", "tutorial", "wiring.png"),
			Buffer.from([137, 80, 78, 71, 0]),
		);
		mkdirSync(join(dir, "pages"), { recursive: true });
		writeFileSync(join(dir, "pages", "about.md"), "# About\n");
		writeFileSync(join(dir, "pages", "index.js"), "export default () => null;\n");
		mkdirSync(join(dir, "blog"), { recursive: true });
		writeFileSync(join(dir, "blog", "2024-01-01-hello.md"), "# Hello\n");
		mkdirSync(join(dir, ".moonwave"), { recursive: true });
		writeFileSync(
			join(dir, ".moonwave", "custom.css"),
			":root {\n\t--ifm-color-primary: #123;\n\t--ifm-color-primary-lightest: #456;\n}\n",
		);
		writeFileSync(join(dir, ".moonwave", "sidebars.js"), "module.exports = {};\n");

		const lines = await initCapturing({ targetDir: dir, fromMoonwave: true });
		const docsDir = join(dir, ".luaudocs");

		// docs/ lands under guide/ with .mdx renamed, displacing the sample page
		const intro = readFileSync(join(docsDir, "guide", "intro.md"), "utf8");
		expect(existsSync(join(docsDir, "guide", "getting-started.md"))).toBe(false);
		// the MDX-only syntax is gone, links moved with the folder, and the
		// fence attributes are respelled the VitePress way
		expect(intro).not.toContain("import ");
		expect(intro).toContain("<!-- draft -->");
		expect(intro).toContain("[setup](/guide/tutorial/setup)");
		expect(intro).toContain("```lua:line-numbers [init.lua]");

		const setup = readFileSync(join(docsDir, "guide", "tutorial", "setup.md"), "utf8");
		expect(setup).toContain("[intro](../intro.md)");
		// co-located assets copy byte-for-byte, and so does the sidecar, which
		// goes on configuring its folder here
		expect(readFileSync(join(docsDir, "guide", "tutorial", "wiring.png"))).toEqual(
			Buffer.from([137, 80, 78, 71, 0]),
		);
		expect(readFileSync(join(docsDir, "guide", "tutorial", "_category_.json"), "utf8")).toBe(
			'{ "label": "Tutorial", "position": 2, "className": "tutorial" }\n',
		);

		// pages/ markdown lands at the docs root; React pages do not convert
		expect(readFileSync(join(docsDir, "about.md"), "utf8")).toBe("# About\n");
		expect(existsSync(join(docsDir, "index.js"))).toBe(false);

		// a draft page stays unpublished, the way moonwave had it
		expect(existsSync(join(docsDir, "guide", "wip.md"))).toBe(false);

		// the stylesheet displaces the template, known Infima renames done and
		// the unknown variable left as written
		const css = readFileSync(join(docsDir, "custom.css"), "utf8");
		expect(css).toContain("--vp-c-brand-1: #123;");
		expect(css).toContain("--ifm-color-primary-lightest: #456;");

		// the landing page is the generated hero rather than the template
		// (moonwave's homepage was generated too), aimed at the first guide
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain("Generated by luaudocs");
		expect(index).toContain("link: /guide/intro");

		// the rebuilt navbar leads with that same first guide page, and an
		// internal item's link is rooted and moved with the page it names
		expect(loadConfig(dir).config.site.nav).toEqual([
			{ text: "Guide", link: "/guide/intro", activeMatch: "^/guide/" },
			{ text: "API", link: "/api/", activeMatch: "^/api/" },
			{ text: "Chat", link: "https://example.test/chat" },
			{ text: "Setup", link: "/guide/tutorial/setup" },
		]);

		// what did not convert is reported, one class per line
		const report = lines.join("\n");
		// the sidecar converted; only the key the sidebar cannot read is named
		expect(report).toContain("guide/tutorial/_category_.json sets className");
		expect(report).toContain("pages/index.js");
		expect(report).toContain("blog/");
		expect(report).toContain(".moonwave/sidebars.js");
		expect(report).toContain("docs/wip.md");
		expect(report).toContain("custom.css still uses --ifm-color-primary-lightest");
		expect(report).toContain("guide/tutorial/setup.md sets slug/id");
		expect(report).toContain("guide/tutorial/setup.md still uses <TOCInline>");
	});

	it("aborts on a sidecar that does not parse, before anything is written", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "moonwave.toml"), 'title = "X"\n');
		mkdirSync(join(dir, "docs", "tutorial"), { recursive: true });
		writeFileSync(join(dir, "docs", "tutorial", "intro.md"), "# Intro\n");
		writeFileSync(
			join(dir, "docs", "tutorial", "_category_.json"),
			'{ "label": "Tutorial", "position": 2, }\n',
		);
		// the same policy as a malformed moonwave.toml: a clean tree, named
		// file, rather than converted pages with no config beside them
		await expect(initProject({ targetDir: dir, fromMoonwave: true })).rejects.toThrow(
			/docs\/tutorial\/_category_\.json/,
		);
		expect(existsSync(join(dir, ".luaudocs"))).toBe(false);
		expect(existsSync(join(dir, "luaudocs.toml"))).toBe(false);
	});

	// moonwave's homepage was generated from config; its branding comes back
	// as a real home-layout index.md, README below as moonwave appended it
	it("writes the homepage branding as an index.md, README included", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			[
				'title = "X"',
				"",
				"[home]",
				"enabled = true",
				"includeReadme = true",
				'bannerImage = "banner.png"',
				"",
				"[[home.features]]",
				'title = "Fast"',
				'description = "Does things quickly."',
				'image = "bolt.svg"',
			].join("\n"),
		);
		writeFileSync(join(dir, "README.md"), "# X\n\nHello.\n");
		const lines = await initCapturing({ targetDir: dir, fromMoonwave: true });

		const index = readFileSync(join(dir, ".luaudocs", "index.md"), "utf8");
		expect(index).toContain("layout: home");
		expect(index).toContain('image: "/banner.png"');
		expect(index).toContain('- title: "Fast"');
		expect(index).toContain('details: "Does things quickly."');
		expect(index).toContain('src: "/bolt.svg"');
		expect(index).toContain("@include: ./.vitepress/generated/readme.md");
		// user-owned from the start: no marker for a build or init to reclaim
		expect(index).not.toContain("Generated by luaudocs");
		// includeReadme carried into the config, so the include already resolves
		expect(existsSync(join(dir, ".luaudocs", ".vitepress", "generated", "readme.md"))).toBe(
			true,
		);
		expect(lines.join("\n")).not.toContain("no equivalent");
	});

	// a hand-written pages/index.md was the site's real homepage; the hero
	// synthesized from [home] must not replace it, --force included
	it("keeps a converted pages/index.md over the synthesized hero", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "moonwave.toml"),
			['title = "X"', "", "[home]", 'bannerImage = "banner.png"'].join("\n"),
		);
		mkdirSync(join(dir, "pages"), { recursive: true });
		writeFileSync(join(dir, "pages", "index.md"), "# Hand-written home\n");
		await initCapturing({ targetDir: dir, fromMoonwave: true, force: true });
		expect(readFileSync(join(dir, ".luaudocs", "index.md"), "utf8")).toBe(
			"# Hand-written home\n",
		);
	});

	// with an existing config surviving the conversion (no --force), the
	// homepage include follows that config: no build under it would write the
	// readme copy the include names
	it("omits the readme include when the surviving config keeps it off", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "luaudocs.toml"), 'title = "Kept"\n');
		writeFileSync(join(dir, "README.md"), "# X\n\nHello.\n");
		writeFileSync(
			join(dir, "moonwave.toml"),
			[
				'title = "X"',
				"",
				"[home]",
				"includeReadme = true",
				'bannerImage = "banner.png"',
			].join("\n"),
		);
		await initCapturing({ targetDir: dir, fromMoonwave: true });
		const index = readFileSync(join(dir, ".luaudocs", "index.md"), "utf8");
		expect(index).toContain("layout: home");
		expect(index).not.toContain("@include");
	});

	it("copies .moonwave/static into public/, never over an existing file", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "moonwave.toml"), 'title = "X"\n');
		mkdirSync(join(dir, ".moonwave", "static"), { recursive: true });
		writeFileSync(join(dir, ".moonwave", "static", "CNAME"), "docs.example.com\n");
		writeFileSync(join(dir, ".moonwave", "static", "logo.png"), "moonwave bytes");
		// public/ already holds a competing copy: the user's file wins
		mkdirSync(join(dir, ".luaudocs", "public"), { recursive: true });
		writeFileSync(join(dir, ".luaudocs", "public", "logo.png"), "mine");

		await initProject({ targetDir: dir, fromMoonwave: true });
		expect(readFileSync(join(dir, ".luaudocs", "public", "CNAME"), "utf8")).toBe(
			"docs.example.com\n",
		);
		expect(readFileSync(join(dir, ".luaudocs", "public", "logo.png"), "utf8")).toBe("mine");
	});

	it("skips the conversion when a config exists and --force was not given", async () => {
		const dir = tempDir();
		writeFileSync(join(dir, "moonwave.toml"), 'title = "Converted"\n');
		writeFileSync(join(dir, "luaudocs.toml"), 'title = "Mine"\n');

		await initProject({ targetDir: dir, fromMoonwave: true });
		expect(loadConfig(dir).config.title).toBe("Mine");
	});
});

describe("the scaffolded Pages workflow", () => {
	const workflowPath = (dir: string) => join(dir, ".github", "workflows", "docs.yml");

	// `build` installs the Lute it pins, so the runner needs nothing beyond node:
	// a toolchain step in this YAML would be a step that pins a second version
	it("is written by every init, with no toolchain step to keep in sync", async () => {
		const dir = tempDir();
		await initProject({ targetDir: dir });
		const yaml = readFileSync(workflowPath(dir), "utf8");
		expect(yaml).not.toContain("rokit");
		expect(yaml).not.toContain("lute");
		expect(yaml).toContain('build --url "${{ steps.pages.outputs.base_url }}"');
		expect(yaml).toContain('path: ".luaudocs/.vitepress/dist"');
		// pinned, because the workflow is user-owned from here on: a floating
		// `npx luaudocs` would pick up a breaking release on an unrelated push
		expect(yaml).toContain(`npx luaudocs@${toolPkg.version} `);
		// the floor this release declares, not a second spelling of it
		expect(yaml).toContain(`node-version: "${/\d+/.exec(toolPkg.engines.node)![0]}"`);
	});

	// a trigger that never matches produces no run and no error, in a file the
	// tool is never allowed to touch again
	it("triggers on the branch the repository is actually on", async () => {
		const dir = tempDir();
		execFileSync("git", ["init", "--initial-branch", "trunk"], { cwd: dir });
		await initProject({ targetDir: dir });

		// before the first commit, which is when init usually runs
		expect(readFileSync(workflowPath(dir), "utf8")).toContain('branches: "trunk"');
	});

	it("falls back to the default branch outside a repository", async () => {
		const dir = tempDir();
		await initProject({ targetDir: dir });
		expect(readFileSync(workflowPath(dir), "utf8")).toContain('branches: "main"');
	});

	it("caches the install against the version that determines it", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "luaudocs.toml"),
			'title = "X"\n\n[source]\nentries = []\n\n[docs]\ndir = "docs"\n',
		);
		await initProject({ targetDir: dir });
		const yaml = readFileSync(workflowPath(dir), "utf8");

		expect(yaml).toContain(`key: \${{ runner.os }}-luaudocs-${toolPkg.version}`);
		// the cached tree moves with [docs] dir, like the artifact path
		expect(yaml).toContain("docs/node_modules");
	});

	it("follows the settled config: a custom [docs] dir moves the artifact path", async () => {
		const dir = tempDir();
		writeFileSync(
			join(dir, "luaudocs.toml"),
			'title = "X"\n\n[source]\nentries = []\n\n[docs]\ndir = "docs"\n',
		);
		await initProject({ targetDir: dir });
		expect(readFileSync(workflowPath(dir), "utf8")).toContain('path: "docs/.vitepress/dist"');
	});

	it("never touches an existing workflow without --force", async () => {
		const dir = tempDir();
		mkdirSync(join(dir, ".github", "workflows"), { recursive: true });
		writeFileSync(workflowPath(dir), "# mine\n");
		await initProject({ targetDir: dir });
		expect(readFileSync(workflowPath(dir), "utf8")).toBe("# mine\n");

		await initProject({ targetDir: dir, force: true });
		expect(readFileSync(workflowPath(dir), "utf8")).toContain("actions/deploy-pages");
	});
});
