/**
 * The docs-root files the build supplies around the user's content: the
 * generated landing page (README when one exists, a hero otherwise) and the
 * .gitignore created only when missing. Ownership is the feature under test:
 * a file without the marker line must never be touched, and one with it is
 * the build's to rewrite.
 */
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { createContext } from "../src/build";
import type { SidebarItem } from "../src/nav";
import { collectGuides, pageTrails, syncSite, type GuideItem } from "../src/site";
import { makeTempDirFactory } from "./helpers";

const tempDir = makeTempDirFactory("luaudocs-site-");

/** A config-less project: a src/ to probe, everything else defaulted. */
function project(): { dir: string; docsDir: string } {
	const dir = tempDir();
	mkdirSync(join(dir, "src"));
	return { dir, docsDir: join(dir, ".luaudocs") };
}

/** The same carrying a config: `[repo]` is what a README's repository-relative
 * link targets respell through, `[docs] url` is what bases them. */
function projectWith(toml: string): { dir: string; docsDir: string } {
	const made = project();
	writeFileSync(join(made.dir, "luaudocs.toml"), toml);
	return made;
}

const REPO_TOML = 'title = "X"\n\n[repo]\nurl = "https://github.com/you/repo"\n';

/** Returns what syncSite warned about, which is most of what these assert on. */
function sync(dir: string, apiSidebar: SidebarItem[] = []): string[] {
	const context = createContext(dir);
	return syncSite(context, { guides: collectGuides(context.docsDir), apiSidebar });
}

/** The one-page sidebar of a build whose extraction emitted something. */
const API_SIDEBAR: SidebarItem[] = [{ text: "Overview", link: "/api/" }];

describe("the generated landing page", () => {
	it("supplies a hero when the project has no README", () => {
		const { dir, docsDir } = project();
		sync(dir, API_SIDEBAR);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain("# Generated by luaudocs");
		expect(index).toContain("layout: home");
		expect(index).toContain(`name: ${JSON.stringify(basename(dir))}`);
		expect(index).toContain("link: /api/");
		// no guide exists, so no dangling Get Started button
		expect(index).not.toContain("Get Started");
	});

	it("omits the API button and nav entry when no module produced a page", () => {
		const { dir, docsDir } = project();
		sync(dir);
		// [source] entries is non-empty (src/ was probed), but nothing emitted:
		// an /api/ link would 404 past VitePress's dead-link check
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).not.toContain("link: /api/");
		const config = readFileSync(join(docsDir, ".vitepress", "config.mts"), "utf8");
		expect(config).not.toContain('"link": "/api/"');
	});

	it("points the hero at the first guide page when one exists", () => {
		const { dir, docsDir } = project();
		mkdirSync(join(docsDir, "guide"), { recursive: true });
		writeFileSync(join(docsDir, "guide", "intro.md"), "# Intro\n");
		sync(dir);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain("text: Get Started");
		expect(index).toContain("link: /guide/intro");
	});

	it("uses README.md when one exists, hide markers honored", () => {
		const { dir, docsDir } = project();
		writeFileSync(
			join(dir, "README.md"),
			"badges\n<!--moonwave-hide-before-this-line-->\n# Lib\nprose\n" +
				"<!--moonwave-hide-after-this-line-->\nrepo-only footer\n",
		);
		sync(dir);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain("# Generated by luaudocs");
		expect(index).toContain("# Lib");
		expect(index).toContain("prose");
		expect(index).not.toContain("badges");
		expect(index).not.toContain("repo-only footer");
	});

	// a moonwave project's README reaches its assets through .moonwave/static/,
	// which the conversion copied into public/; a code span showing the path is
	// a mention, not a target
	it("respells .moonwave/static/ targets to the site root", () => {
		const { dir, docsDir } = project();
		mkdirSync(join(docsDir, "public"), { recursive: true });
		writeFileSync(join(docsDir, "public", "logo.svg"), "<svg />");
		writeFileSync(
			join(dir, "README.md"),
			'<img src=".moonwave/static/logo.svg" />\n\nsee `.moonwave/static/logo.svg`\n',
		);
		sync(dir);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain('src="/logo.svg"');
		expect(index).toContain("`.moonwave/static/logo.svg`");
	});

	it("leaves .moonwave/static/ targets to [repo] when nothing was copied", () => {
		const { dir, docsDir } = projectWith(REPO_TOML);
		writeFileSync(join(dir, "README.md"), '<img src=".moonwave/static/logo.svg" />\n');
		sync(dir);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain(
			'src="https://github.com/you/repo/raw/main/.moonwave/static/logo.svg"',
		);
	});

	it("respells repository-relative targets through [repo]", () => {
		const { dir, docsDir } = projectWith(REPO_TOML);
		writeFileSync(
			join(dir, "README.md"),
			[
				"[contrib](CONTRIBUTING.md) [license](./LICENSE.txt#terms)",
				"![shot](media/shot.png) [that shot](media/shot.png)",
				"[angled](<CONTRIBUTING.md>)",
				"[guide](.luaudocs/guide/intro.md) [asset](.luaudocs/public/logo.svg)",
				"[site](https://example.com) [top](#usage)",
				"see `CONTRIBUTING.md`",
			].join("\n\n") + "\n",
		);
		expect(sync(dir)).toEqual([]);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain("(https://github.com/you/repo/blob/main/CONTRIBUTING.md)");
		expect(index).toContain("(https://github.com/you/repo/blob/main/LICENSE.txt#terms)");
		// the route follows the slot, not the extension: rendered inline it needs
		// the bytes, linked to it wants the page
		expect(index).toContain("![shot](https://github.com/you/repo/raw/main/media/shot.png)");
		expect(index).toContain(
			"[that shot](https://github.com/you/repo/blob/main/media/shot.png)",
		);
		// `<>` around a destination is syntax, and stays syntax
		expect(index).toContain(
			"[angled](<https://github.com/you/repo/blob/main/CONTRIBUTING.md>)",
		);
		expect(index).toContain("(/guide/intro)");
		expect(index).toContain("(/logo.svg)");
		// already resolvable, and a mention in code: all verbatim
		expect(index).toContain("(https://example.com)");
		expect(index).toContain("(#usage)");
		expect(index).toContain("`CONTRIBUTING.md`");
	});

	it("warns once about repository links no [repo] can point anywhere", () => {
		const { dir, docsDir } = project();
		writeFileSync(
			join(dir, "README.md"),
			"[contrib](CONTRIBUTING.md)\n\n[again](CONTRIBUTING.md) [license](LICENSE.txt)\n",
		);
		expect(sync(dir)).toEqual([
			"warning: README.md links CONTRIBUTING.md, LICENSE.txt, which the generated " +
				"site does not serve; set [repo] to point them at the repository",
		]);
		// left as written: the warning names the fix, a rewrite would guess
		expect(readFileSync(join(docsDir, "index.md"), "utf8")).toContain("(CONTRIBUTING.md)");
	});

	it("warns about a target climbing above the repository root", () => {
		const { dir } = projectWith(REPO_TOML);
		writeFileSync(join(dir, "README.md"), "[shared](../shared/README.md)\n");
		expect(sync(dir)).toEqual([
			"warning: README.md links ../shared/README.md, which the generated " +
				"site does not serve and [repo] cannot reach",
		]);
	});

	// the code span between them puts definitions and uses in different segments
	it("routes a reference definition through the slot its references use", () => {
		const { dir, docsDir } = projectWith(REPO_TOML);
		writeFileSync(
			join(dir, "README.md"),
			[
				"![badge][build] [the file][doc]",
				"see `x`",
				"[build]: media/badge.svg",
				"[doc]: CONTRIBUTING.md",
			].join("\n\n") + "\n",
		);
		expect(sync(dir)).toEqual([]);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain("[build]: https://github.com/you/repo/raw/main/media/badge.svg");
		expect(index).toContain("[doc]: https://github.com/you/repo/blob/main/CONTRIBUTING.md");
	});

	it("carries the site base on a raw HTML href, and nowhere else", () => {
		const { dir, docsDir } = projectWith(
			'title = "X"\n\n[docs]\nurl = "https://you.github.io/repo"\n',
		);
		mkdirSync(join(docsDir, "public"), { recursive: true });
		writeFileSync(join(docsDir, "public", "logo.svg"), "<svg />");
		writeFileSync(
			join(dir, "README.md"),
			'<img src=".moonwave/static/logo.svg" />\n\n![shot](.luaudocs/public/shot.png)\n\n' +
				'[guide](.luaudocs/guide/intro.md)\n\n<a href=".luaudocs/guide/intro.md">g</a>\n',
		);
		expect(sync(dir)).toEqual([]);
		const index = readFileSync(join(docsDir, "index.md"), "utf8");
		expect(index).toContain('src="/logo.svg"');
		expect(index).toContain("(/shot.png)");
		expect(index).toContain("(/guide/intro)");
		expect(index).toContain('href="/repo/guide/intro"');
	});

	it("says nothing about a README the site never renders", () => {
		const { dir, docsDir } = project();
		writeFileSync(join(dir, "README.md"), "[contrib](CONTRIBUTING.md)\n");
		mkdirSync(docsDir, { recursive: true });
		writeFileSync(join(docsDir, "index.md"), "# Mine\n");
		expect(sync(dir)).toEqual([]);
	});

	it("keeps rewriting a marked page, and never touches an unmarked one", () => {
		const { dir, docsDir } = project();
		sync(dir);
		// still marked: a README appearing later replaces the hero
		writeFileSync(join(dir, "README.md"), "# Readme\n");
		sync(dir);
		expect(readFileSync(join(docsDir, "index.md"), "utf8")).toContain("# Readme");
		// the user takes over: the next sync leaves the file alone
		writeFileSync(join(docsDir, "index.md"), "# Mine\n");
		sync(dir);
		expect(readFileSync(join(docsDir, "index.md"), "utf8")).toBe("# Mine\n");
	});
});

describe("the generated .gitignore", () => {
	it("is created only when missing, covering everything the build wrote", () => {
		const { dir, docsDir } = project();
		sync(dir);
		const path = join(docsDir, ".gitignore");
		const ignore = readFileSync(path, "utf8");
		for (const line of [
			".vitepress/",
			"api/",
			"package.json",
			"node_modules/",
			"index.md",
			".gitignore",
		]) {
			expect(ignore, line).toContain(line);
		}
		writeFileSync(path, "# mine\n");
		sync(dir);
		expect(readFileSync(path, "utf8")).toBe("# mine\n");
	});

	it("does not ignore a landing page the user owns", () => {
		const { dir, docsDir } = project();
		mkdirSync(docsDir, { recursive: true });
		writeFileSync(join(docsDir, "index.md"), "# Mine\n");
		sync(dir);
		expect(readFileSync(join(docsDir, ".gitignore"), "utf8")).not.toMatch(/^index\.md$/m);
	});
});

describe("[[site.head]]", () => {
	it("bakes every entry into the site config after the derived tags", () => {
		const dir = tempDir();
		mkdirSync(join(dir, "src"));
		writeFileSync(
			join(dir, "luaudocs.toml"),
			[
				'title = "X"',
				"",
				"[[site.head]]",
				'tag = "script"',
				'attrs = { defer = "true", src = "https://plausible.io/js/script.js", "data-domain" = "docs.example.com" }',
				"",
				"[[site.head]]",
				'tag = "script"',
				'content = "track()"',
				"",
			].join("\n"),
		);
		const context = createContext(dir);
		syncSite(context, { guides: [], apiSidebar: [] });
		const baked = readFileSync(join(dir, ".luaudocs", ".vitepress", "config.mts"), "utf8");
		expect(baked).toContain('"data-domain": "docs.example.com"');
		expect(baked).toContain('"track()"');
		// the derived og tags still lead, so the user's entries append
		expect(baked.indexOf("og:site_name")).toBeLessThan(baked.indexOf("data-domain"));
	});
});

describe("[site] ogImage", () => {
	it("bakes the og:image tag and the card type it implies", () => {
		const dir = tempDir();
		mkdirSync(join(dir, "src"));
		writeFileSync(
			join(dir, "luaudocs.toml"),
			[
				'title = "X"',
				"",
				"[site]",
				'ogImage = "/og.png"',
				"",
				"[docs]",
				'url = "https://docs.example.com"',
				"",
			].join("\n"),
		);
		const context = createContext(dir);
		syncSite(context, { guides: [], apiSidebar: [] });
		const baked = readFileSync(join(dir, ".luaudocs", ".vitepress", "config.mts"), "utf8");
		expect(baked).toContain('"og:image"');
		expect(baked).toContain("https://docs.example.com/og.png");
		expect(baked).toContain("summary_large_image");
	});
});

describe("the derived navbar", () => {
	it("marks a section entry current across the section, a single page only on it", () => {
		const { dir, docsDir } = project();
		mkdirSync(join(docsDir, "guide"), { recursive: true });
		writeFileSync(join(docsDir, "guide", "intro.md"), "# Intro\n");
		writeFileSync(join(dir, "CHANGELOG.md"), "# Changelog\n");
		sync(dir, API_SIDEBAR);
		const baked = readFileSync(join(docsDir, ".vitepress", "config.mts"), "utf8");
		expect(baked).toContain('"activeMatch": "^/guide/"');
		expect(baked).toContain('"activeMatch": "^/api/"');
		// the changelog is one page, so its link is the whole of its match
		expect(baked).toMatch(/"text": "Changelog",\n\t+"link": "\/changelog"\n/);
	});
});

describe("[site] siteTitle", () => {
	it("bakes the navbar override, false included", () => {
		const dir = tempDir();
		mkdirSync(join(dir, "src"));
		const config = join(dir, "luaudocs.toml");
		const baked = join(dir, ".luaudocs", ".vitepress", "config.mts");
		writeFileSync(config, 'title = "X"\n\n[site]\nsiteTitle = "Short"\n');
		syncSite(createContext(dir), { guides: [], apiSidebar: [] });
		expect(readFileSync(baked, "utf8")).toContain('siteTitle: "Short",');

		writeFileSync(config, 'title = "X"\n\n[site]\nsiteTitle = false\n');
		syncSite(createContext(dir), { guides: [], apiSidebar: [] });
		expect(readFileSync(baked, "utf8")).toContain("siteTitle: false,");
	});
});

describe("the generated changelog page", () => {
	it("mirrors CHANGELOG.md while it exists, and removes only its own copy", () => {
		const { dir, docsDir } = project();
		writeFileSync(join(dir, "CHANGELOG.md"), "# Changelog\n\n- first\n");
		sync(dir);
		const target = join(docsDir, "changelog.md");
		// the generated frontmatter doubles as the ownership marker here
		const written = readFileSync(target, "utf8");
		expect(written.startsWith('---\ntitle: "Changelog"')).toBe(true);
		expect(written).toContain("- first");

		// the source is gone: the generated copy must not keep publishing it
		rmSync(join(dir, "CHANGELOG.md"));
		sync(dir);
		expect(existsSync(target)).toBe(false);

		// a user-owned changelog.md (no marker) is never the build's to delete
		writeFileSync(target, "# Mine\n");
		sync(dir);
		expect(readFileSync(target, "utf8")).toBe("# Mine\n");
	});
});

describe("build --url", () => {
	it("overrides [docs] url and reaches the baked site config", () => {
		const dir = tempDir();
		mkdirSync(join(dir, "src"));
		writeFileSync(
			join(dir, "luaudocs.toml"),
			'title = "X"\n\n[docs]\nurl = "https://old.example.com"\n',
		);
		const context = createContext(dir, { url: "https://user.github.io/repo/" });
		expect(context.config.docs.url).toBe("https://user.github.io/repo");
		syncSite(context, { guides: [], apiSidebar: [] });
		const baked = readFileSync(join(dir, ".luaudocs", ".vitepress", "config.mts"), "utf8");
		expect(baked).toContain('base: "/repo/"');
		expect(baked).toContain("https://user.github.io/repo");
		expect(baked).not.toContain("old.example.com");
	});
});

/** A guide tree on disk, keyed by path under `<docs>/guide/`. */
function writeGuides(docsDir: string, files: Record<string, string>): void {
	for (const [rel, text] of Object.entries(files)) {
		const abs = join(docsDir, "guide", rel);
		mkdirSync(dirname(abs), { recursive: true });
		writeFileSync(abs, text);
	}
}

/** That tree as the sidebar walk and the trail builder read it. */
function guidesOf(files: Record<string, string>): GuideItem[] {
	const docsDir = join(tempDir(), ".luaudocs");
	writeGuides(docsDir, files);
	return collectGuides(docsDir);
}

describe("the guides sidebar", () => {
	/** A page carrying only the frontmatter the sidebar reads. */
	function page(title: string, ...keys: string[]): string {
		return ["---", `title: ${title}`, ...keys, "---", "", `The ${title} page.`, ""].join("\n");
	}

	/** Titles in sidebar order, a group written `Folder [child, child]`. */
	function outline(items: GuideItem[]): string[] {
		return items.map((item) =>
			item.items ? `${item.text} [${outline(item.items).join(", ")}]` : item.text,
		);
	}

	/** The baked guide sidebar of a project holding these guide files. */
	function bakedSidebar(files: Record<string, string>): string {
		const { dir, docsDir } = project();
		writeGuides(docsDir, files);
		sync(dir, API_SIDEBAR);
		return readFileSync(join(docsDir, ".vitepress", "generated", "sidebar.ts"), "utf8");
	}

	it("reads a position against the siblings, never the whole tree", () => {
		const guides = guidesOf({
			"intro.md": page("Intro", "sidebar_position: 1"),
			"deploying.md": page("Deploying", "sidebar_position: 3"),
			"reference/index.md": page("Overview", "sidebar_position: 2"),
			"reference/cli.md": page("CLI", "sidebar_position: 1"),
			"reference/tags.md": page("Tags", "sidebar_position: 2"),
		});
		// the group sits at 2 because its own index.md says so: the pages inside
		// it number from 1 like the pages beside it, and that 1 never pulls the
		// group to the front
		expect(outline(guides)).toEqual(["Intro", "Reference [Overview, CLI, Tags]", "Deploying"]);
	});

	it("leads a group with its index page, whatever positions it and its siblings declare", () => {
		const guides = guidesOf({
			"reference/index.md": page("Overview", "sidebar_position: 9"),
			"reference/aardvark.md": page("Aardvark", "sidebar_position: 0"),
			"reference/cli.md": page("CLI", "sidebar_position: 1"),
		});
		expect(outline(guides)).toEqual(["Reference [Overview, Aardvark, CLI]"]);
	});

	it("leads the top level with guide/index.md the same way", () => {
		const guides = guidesOf({
			"index.md": page("Overview", "sidebar_position: 9"),
			"getting-started.md": page("Getting Started", "sidebar_position: 1"),
		});
		// the position on a top-level index page places nothing: there is no
		// folder for it to place, and the page itself leads regardless
		expect(outline(guides)).toEqual(["Overview", "Getting Started"]);
		expect(guides[0]!.link).toBe("/guide/");
	});

	it("accepts any number docusaurus does as a position", () => {
		const guides = guidesOf({
			"two.md": page("Two", "sidebar_position: 2"),
			"three.md": page("Three", "sidebar_position: 3"),
			"between/_category_.json": '{ "position": 2.5 }\n',
			"between/one.md": page("One"),
			"first/_category_.json": '{ "position": -1 }\n',
			"first/one.md": page("One"),
			"nowhere/_category_.json": '{ "position": "high" }\n',
			"nowhere/one.md": page("One"),
		});
		// a fractional position slots between its neighbors, a negative one
		// leads, and a word sorts as if no position were declared
		expect(outline(guides)).toEqual([
			"First [One]",
			"Two",
			"Between [One]",
			"Three",
			"Nowhere [One]",
		]);
	});

	it("reads each source's own keys: position is the sidecar's, sidebar_position the page's", () => {
		const guides = guidesOf({
			"sidecar/_category_.json": '{ "sidebar_position": 1 }\n',
			"sidecar/one.md": page("One"),
			"own/index.md": page("Overview", "position: 1"),
			"own/one.md": page("One"),
			"placed/_category_.json": '{ "position": 2 }\n',
			"placed/one.md": page("One"),
		});
		// neither stray key places its folder, so both sort last by label
		expect(outline(guides)).toEqual(["Placed [One]", "Own [Overview, One]", "Sidecar [One]"]);
	});

	it("sorts a folder declaring no position last, as it does a page", () => {
		const guides = guidesOf({
			"intro.md": page("Intro", "sidebar_position: 1"),
			"extras/one.md": page("One", "sidebar_position: 1"),
			"zzz.md": page("Later"),
		});
		// both are unpositioned, so the label breaks the tie between them
		expect(outline(guides)).toEqual(["Intro", "Extras [One]", "Later"]);
	});

	it("takes a group's label and position from the sidecar beside its pages", () => {
		const guides = guidesOf({
			"intro.md": page("Intro", "sidebar_position: 1"),
			"reference/_category_.json": '{ "label": "API Reference", "position": 2 }\n',
			"reference/cli.md": page("CLI"),
			"zzz/_category_.json": '{ "position": 3 }\n',
			"zzz/one.md": page("One"),
		});
		// the label replaces the folder name; a sidecar setting none keeps it
		expect(outline(guides)).toEqual(["Intro", "API Reference [CLI]", "Zzz [One]"]);
	});

	it("lets the sidecar outrank the folder's index page, key by key", () => {
		const guides = guidesOf({
			"reference/_category_.json": '{ "position": 1 }\n',
			"reference/index.md": page("Overview", "sidebar_position: 9", "collapsed: true"),
			"reference/cli.md": page("CLI"),
			"other/one.md": page("One", "sidebar_position: 1"),
		});
		// the position is the sidecar's; the collapsed state it leaves unset is
		// still the index page's to give
		expect(outline(guides)).toEqual(["Reference [Overview, CLI]", "Other [One]"]);
		expect(guides[0]!.collapsed).toBe(true);
	});

	it("reads the yaml spelling of the sidecar the same way", () => {
		const guides = guidesOf({
			"reference/_category_.yml": "label: Reference Guide\nposition: 1\ncollapsed: true\n",
			"reference/cli.md": page("CLI"),
		});
		expect(outline(guides)).toEqual(["Reference Guide [CLI]"]);
		expect(guides[0]!.collapsed).toBe(true);
	});

	it("keeps a yaml value on its key's line, so a blank key reads as unset", () => {
		const guides = guidesOf({
			"reference/_category_.yml": "label:\nposition: 2\n",
			"reference/cli.md": page("CLI"),
			"intro.md": page("Intro", "sidebar_position: 1"),
		});
		// the blank label falls back to the folder name rather than swallowing
		// the position line as its value, which is still read as the position
		expect(outline(guides)).toEqual(["Intro", "Reference [CLI]"]);
	});

	it("reads the booleans in the cases YAML spells them", () => {
		const guides = guidesOf({
			"closed/_category_.yml": "collapsed: True\n",
			"closed/one.md": page("One"),
			"fixed/_category_.yml": "collapsible: False\n",
			"fixed/one.md": page("One"),
		});
		expect(guides.map((item) => [item.text, item.collapsed, item.collapsible])).toEqual([
			["Closed", true, undefined],
			["Fixed", undefined, false],
		]);
	});

	it("fails on a sidecar that does not parse, rather than ordering by accident", () => {
		expect(() =>
			guidesOf({
				"reference/_category_.json": '{ "label": "Reference", }\n',
				"reference/cli.md": page("CLI"),
			}),
		).toThrow(/_category_\.json/);
	});

	it("leaves out an underscore-prefixed folder or page, in the sidebar and the build", () => {
		const { dir, docsDir } = project();
		writeGuides(docsDir, {
			"intro.md": page("Intro"),
			"_partial.md": page("Partial"),
			"_drafts/one.md": page("One"),
			"reference/cli.md": page("CLI"),
			"reference/_wip/two.md": page("Two"),
		});
		expect(outline(collectGuides(docsDir))).toEqual(["Intro", "Reference [CLI]"]);
		sync(dir, API_SIDEBAR);
		const config = readFileSync(join(docsDir, ".vitepress", "config.mts"), "utf8");
		expect(config).toContain('srcExclude: ["guide/**/_*.md","guide/**/_*/**"]');
	});

	it("heads the pages with one Guide section, or with each folder when nothing sits loose", () => {
		const wrapped = bakedSidebar({
			"intro.md": page("Intro"),
			"reference/cli.md": page("CLI"),
		});
		expect(wrapped).toMatch(/guideSidebar[^]*"text": "Guide",\n\t+"items"/);
		const sections = bakedSidebar({
			"basics/index.md": page("Basics"),
			"basics/setup.md": page("Setup"),
			"reference/cli.md": page("CLI"),
		});
		expect(sections).not.toContain('"text": "Guide"');
		// the folders themselves are the top-level sections, in their order
		expect(sections).toMatch(/guideSidebar[^]*= \[\n\t\{\n\t\t"text": "Basics"/);
		expect(sections).toMatch(/\n\t\{\n\t\t"text": "Reference"/);
	});

	it("gives a folder heading its own section no toggle unless it asks for one", () => {
		const baked = bakedSidebar({
			"bare/one.md": page("One"),
			"closed/_category_.json": '{ "collapsed": true }\n',
			"closed/one.md": page("One"),
			"open/_category_.json": '{ "collapsible": true }\n',
			"open/one.md": page("One"),
		});
		expect(baked).toMatch(/"text": "Bare",\n\t+"items"/);
		expect(baked).toMatch(/"text": "Closed",\n\t+"collapsed": true/);
		expect(baked).toMatch(/"text": "Open",\n\t+"collapsed": false/);
	});

	it("bakes the collapsed state, and no key at all where a group never collapses", () => {
		const baked = bakedSidebar({
			// a loose page keeps the groups nested under the Guide heading
			"intro.md": page("Intro"),
			"closed/_category_.json": '{ "collapsed": true }\n',
			"closed/one.md": page("One"),
			"asked/index.md": page("Overview", "collapsed: true"),
			"asked/one.md": page("One"),
			"fixed/_category_.json": '{ "collapsible": false }\n',
			"fixed/one.md": page("One"),
			"bare/one.md": page("One"),
		});
		expect(baked).toMatch(/"text": "Closed",\n\t+"collapsed": true/);
		expect(baked).toMatch(/"text": "Asked",\n\t+"collapsed": true/);
		// VitePress reads a group carrying no collapsed key as one with no
		// toggle at all, which is what collapsible: false asks for
		expect(baked).toMatch(/"text": "Fixed",\n\t+"items"/);
		// a group nothing configures is collapsible, and open
		expect(baked).toMatch(/"text": "Bare",\n\t+"collapsed": false/);
	});
});

describe("page trails", () => {
	const HOME = { text: "Home", link: "/" };

	it("hangs a guide page off Home, its folders between", () => {
		const guides = guidesOf({
			"getting-started.md": "# Getting Started\n",
			"reference/tags.md": "# Tags\n",
		});
		const trails = pageTrails(guides, undefined, false);
		expect(trails["guide/getting-started.md"]).toEqual([HOME]);
		// no reference/index.md, so the folder is a label with nowhere to go
		expect(trails["guide/reference/tags.md"]).toEqual([HOME, { text: "Reference" }]);
	});

	it("links a folder to its own index page, which never trails itself", () => {
		const guides = guidesOf({
			"reference/index.md": "# Reference\n",
			"reference/tags.md": "# Tags\n",
		});
		const trails = pageTrails(guides, undefined, false);
		expect(trails["guide/reference/tags.md"]).toEqual([
			HOME,
			{ text: "Reference", link: "/guide/reference/" },
		]);
		expect(trails["guide/reference/index.md"]).toEqual([HOME]);
	});

	it("puts Home above the API trails the emitter derived", () => {
		const api = new Map([
			// the emitter's own map: the index page included, trailed by nothing
			["index.md", []],
			["Flux.md", [{ text: "Overview", link: "/api/" }]],
			[
				"Queue.md",
				[
					{ text: "Overview", link: "/api/" },
					{ text: "Flux", link: "/api/Flux" },
				],
			],
		]);
		const trails = pageTrails([], api, true);
		expect(trails["api/Queue.md"]).toEqual([
			HOME,
			{ text: "Overview", link: "/api/" },
			{ text: "Flux", link: "/api/Flux" },
		]);
		// the API index is the section's root, and the changelog a page beside it
		expect(trails["api/index.md"]).toEqual([HOME]);
		expect(trails["changelog.md"]).toEqual([HOME]);
	});

	it("leaves out what the site does not publish", () => {
		const trails = pageTrails([], new Map(), false);
		// no pages emitted, so no /api/ index exists to trail; no changelog either
		expect(trails).toEqual({});
	});

	it("bakes the map the render-time rule reads", () => {
		const { dir, docsDir } = project();
		mkdirSync(join(docsDir, "guide"), { recursive: true });
		writeFileSync(join(docsDir, "guide", "usage.md"), "# Usage\n");
		sync(dir, API_SIDEBAR);
		const baked = readFileSync(join(docsDir, ".vitepress", "generated", "trails.ts"), "utf8");
		expect(baked).toContain("export const pageTrails");
		expect(baked).toContain('"guide/usage.md"');
		const config = readFileSync(join(docsDir, ".vitepress", "config.mts"), "utf8");
		expect(config).toContain('from "./generated/trails.ts"');
		expect(config).toContain("installMarkupRule(md, pageTrails)");
	});
});
