// @generated by luaudocs. Do not edit; regenerated by every build.
//
// Icons for code-group tabs and fence titles, passed to the group-icons vite
// plugin by the baked config as its `customIcon` map. The plugin matches a
// title against these first, then its own map (npm, toml, bash, ...), by
// keyword and then by file extension.

/** GitHub's mark, minted per theme: an icon is a background image, so it
 * cannot inherit a color and a single dark glyph would vanish in dark mode. */
const githubMark = (fill: string) =>
	`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="1em" height="1em"><path fill="${fill}" d="M12 .297c-6.63 0-12 5.373-12 12c0 5.303 3.438 9.8 8.205 11.385c.6.113.82-.258.82-.577c0-.285-.01-1.04-.015-2.04c-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729c1.205.084 1.838 1.236 1.838 1.236c1.07 1.835 2.809 1.305 3.495.998c.108-.776.417-1.305.76-1.605c-2.665-.3-5.466-1.332-5.466-5.93c0-1.31.465-2.38 1.235-3.22c-.135-.303-.54-1.523.105-3.176c0 0 1.005-.322 3.3 1.23c.96-.267 1.98-.399 3-.405c1.02.006 2.04.138 3 .405c2.28-1.552 3.285-1.23 3.285-1.23c.645 1.653.24 2.873.12 3.176c.765.84 1.23 1.91 1.23 3.22c0 4.61-2.805 5.625-5.475 5.92c.42.36.81 1.096.81 2.22c0 1.606-.015 2.896-.015 3.286c0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/></svg>`;

/** What the plugin's own map misses: Luau, and a tab named for the repo. A key
 * with no dot is a substring keyword, tried before any extension, so a bare
 * `luau` would claim `luaudocs.toml` and a bare `lua` would claim `evaluate.ts`. */
export const codeIcons = {
	".luau": "vscode-icons:file-type-luau",
	".lua": "vscode-icons:file-type-lua",
	github: { light: githubMark("#24292f"), dark: githubMark("#e6edf3") },
};
