// @generated by luaudocs. Do not edit; regenerated by every build.
//
// Inline code highlighting via a pandoc-style language annotation:
//
//     `Flux.state(0)`{luau} renders through Shiki like a fenced block.
//
// The highlighter is VitePress's own, captured by the generated config's
// markdown.shikiSetup hook after VitePress creates it; no second Shiki
// instance exists, and inline code follows the fenced examples' themes for
// free. Only luau/lua annotations are claimed; anything else (`{#id}`,
// `{.class}`, an unknown lang) is left for VitePress's markdown-it-attrs,
// which runs next.
import type MarkdownIt from "markdown-it";
import type { Highlighter } from "shiki";

// the exact default pair VitePress highlights fences with; a baked constant
// because the generated site has no theme override surface
const THEMES = { light: "github-light", dark: "github-dark" } as const;

/** The languages an inline annotation may claim; src/site.ts bakes this list
 * into the config that preloads them. */
export const LANGUAGES: readonly string[] = ["luau", "lua"];

/**
 * The `{...}` suffix a code span may carry. Shared with the emitter's llms.txt
 * stripper (src/markdown.ts), so widening the character class here widens what
 * that recognizes too. Only the *shape* is shared, not the verdict.
 */
export const ANNOTATION_PATTERN = "\\{([\\w+#.-]+)\\}";

const ANNOTATION = new RegExp(`^${ANNOTATION_PATTERN}`);

export function inlineHighlightPlugin(
	md: MarkdownIt,
	getHighlighter: () => Highlighter | undefined,
): void {
	md.core.ruler.after("inline", "inline_highlight_annotate", (state) => {
		for (const block of state.tokens) {
			if (block.type !== "inline" || !block.children) continue;
			const children = block.children;
			for (let i = 0; i < children.length; i++) {
				const tok = children[i];
				if (!tok || tok.type !== "code_inline") continue;
				const next = children[i + 1];
				if (!next || next.type !== "text") continue;
				const m = next.content.match(ANNOTATION);
				if (!m || !LANGUAGES.includes(m[1]!)) continue;
				tok.info = m[1]!;
				next.content = next.content.slice(m[0].length);
			}
		}
		return true;
	});

	const fallback =
		md.renderer.rules.code_inline ??
		((tokens, idx) => `<code>${md.utils.escapeHtml(tokens[idx]?.content ?? "")}</code>`);

	md.renderer.rules.code_inline = (tokens, idx, options, env, self) => {
		const tok = tokens[idx];
		if (!tok?.info) return fallback(tokens, idx, options, env, self);

		const hl = getHighlighter();
		if (!hl) return fallback(tokens, idx, options, env, self);
		const useLang = hl.getLoadedLanguages().includes(tok.info) ? tok.info : "text";

		try {
			const inner = hl.codeToHtml(tok.content, {
				lang: useLang,
				themes: THEMES,
				defaultColor: false,
				structure: "inline", // just colored spans, no <pre>/<code>/line wrappers
			});
			return `<code class="shiki-inline">${inner}</code>`;
		} catch {
			return fallback(tokens, idx, options, env, self);
		}
	};
}
