// @generated by luaudocs. Do not edit; regenerated by every build.
//
// Every rewrite applied to a page's raw source, installed as one markdown-it
// core rule by the baked config.mts. Two are Docusaurus compatibility (`:::note`
// admonitions become VitePress containers, and `<Tabs>` / `<TabItem>` groups
// become the tab strip `::: code-group` renders); `<Frame>` is luaudocs's own.
// The same rule prepends each page's navigation trail, which a guide page (the
// user's own file) can only be given at render time.
//
// They share one masking pass, so an example that merely *shows* any of this
// syntax inside a fence is never rewritten.
//
// Synced into user sites, so it cannot import from src/; the fence splitter
// therefore lives here, and the emitter imports it through src/markdown.ts.
import type MarkdownIt from "markdown-it";

// the up-to-3-space indent markdown-it accepts, then a fence's marker run
const FENCE_OPENER = /^[ \t]{0,3}(`{3,}|~{3,})/;

/**
 * Splits markdown into segments alternating outside/inside fenced code blocks
 * (odd indices are fences), so rewrites can leave example code verbatim. A
 * fence closes only on the same marker character, at least as long as the
 * opener, with nothing after it. An unterminated fence runs to the end,
 * conservatively rewriting nothing.
 *
 * CommonMark's 3-space cap on the opener is enforced, so a 4-space-indented
 * block that *shows* a fence cannot invert the parity of every later segment.
 * The cap is really relative to the containing block, so a fence deep inside a
 * list item is missed and treated as prose: the lesser error.
 */
export function splitFences(text: string): string[] {
	if (!text.includes("```") && !text.includes("~~~")) {
		return [text];
	}
	const parts: string[] = [];
	let segmentStart = 0;
	let offset = 0;
	let fence: { char: string; length: number } | undefined;
	for (const line of text.split(/(?<=\n)/)) {
		const marker = line.match(FENCE_OPENER)?.[1];
		if (!fence) {
			if (marker) {
				parts.push(text.slice(segmentStart, offset));
				segmentStart = offset;
				fence = { char: marker[0]!, length: marker.length };
			}
		} else if (
			marker &&
			marker[0] === fence.char &&
			marker.length >= fence.length &&
			/^[ \t]*$/.test(line.slice(line.indexOf(marker) + marker.length).trimEnd())
		) {
			parts.push(text.slice(segmentStart, offset + line.length));
			segmentStart = offset + line.length;
			fence = undefined;
		}
		offset += line.length;
	}
	parts.push(text.slice(segmentStart));
	return parts;
}

/** One HTML escaper for element text and double-quoted attributes alike. */
export function escapeHtml(text: string): string {
	return text
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

/** Docusaurus admonition kinds -> VitePress container kinds. */
const ADMONITION_MAP: Record<string, string> = {
	note: "info",
	tip: "tip",
	info: "info",
	caution: "warning",
	warning: "warning",
	danger: "danger",
};

/**
 * Line-anchored, tolerating the up-to-3-space indent markdown-it accepts;
 * unknown kinds and bare `:::` closers (identical in both dialects) pass
 * through. Docusaurus 3 spells a custom title in brackets (`:::tip[Title]`);
 * VitePress takes it bare.
 */
function rewriteAdmonitions(text: string): string {
	return text.replace(
		/^([ \t]{0,3}):::(\w+)(.*)$/gm,
		(match, indent: string, kind: string, rest: string) => {
			const mapped = ADMONITION_MAP[kind.toLowerCase()];
			if (!mapped) {
				return match;
			}
			const title = rest.match(/^\[([^\]]*)\][ \t\r]*$/);
			return `${indent}::: ${mapped}${title ? ` ${title[1]}` : rest}`;
		},
	);
}

/** The component tags the rewrites below consume, exported for the moonwave
 * converter's leftover-component report. */
export const REWRITTEN_COMPONENTS = ["Tabs", "TabItem", "Frame"] as const;

/** A whole element, opener and closer each alone on their line. Group 1 is the
 * attribute list, group 2 the body. Non-greedy: these do not nest. */
function blockElement(tag: string): RegExp {
	return new RegExp(
		`^[ \\t]{0,3}<${tag}\\b([^>]*)>[ \\t]*\\r?\\n([\\s\\S]*?)^[ \\t]*<\\/${tag}>[ \\t]*$`,
		"gm",
	);
}

const TAB_GROUP = blockElement("Tabs");
const TAB_ITEM = /<TabItem\b([^>]*)>([\s\S]*?)<\/TabItem>/g;
// What a fence is masked to while a group is matched: a character markdown
// source cannot carry, so a marker never collides with the prose around it.
const MARK = "\u0000";
const MASKED_FENCE = new RegExp(`^${MARK}(\\d+)${MARK}$`);
const MASKED_FENCES = new RegExp(`${MARK}(\\d+)${MARK}`, "g");
// the opener line of a fence: everything Shiki reads, and where `active` goes
const FENCE_INFO = new RegExp(`${FENCE_OPENER.source}[^\\n]*`);
// a VitePress fence title, `[init.luau]`, anywhere in that opener line
const FENCE_TITLE = /\s*\[(?:[^[\]]|\[[^[\]]*\])*\]/;

/** A body ending in a fence already carries that fence's newline. */
function closeGap(body: string): string {
	return body.endsWith(MARK) ? "\n" : "\n\n";
}

/** A double- or single-quoted JSX attribute off a `<TabItem>` attribute list. */
function attr(attrs: string, name: string): string | undefined {
	return attrs.match(new RegExp(`\\b${name}\\s*=\\s*(["'])(.*?)\\1`))?.[2];
}

/** Docusaurus's bare `default` flag, tested with quoted values stripped so
 * `label="default"` never counts. */
function isDefault(attrs: string): boolean {
	return /\bdefault\b/.test(attrs.replace(/(["']).*?\1/g, ""));
}

/**
 * Rewrites docusaurus/moonwave tab groups into the markup VitePress's own
 * `::: code-group` container produces. `fences` holds what the markers stand
 * for.
 *
 * Writing the container's OUTPUT rather than its syntax is what lets a tab
 * hold prose: the container mints a tab per fence in its body. VitePress
 * styles and switches the markup by class, so no component or script ships.
 */
function rewriteTabs(masked: string, fences: string[]): string {
	// radio names only have to be unique per *page* (a shared `name` would let
	// one group untick another's tab), and a page is rewritten in one call
	let groups = 0;
	return masked.replace(TAB_GROUP, (group, _attrs: string, body: string) => {
		const items = [...body.matchAll(TAB_ITEM)].map(([, attrs = "", content = ""]) => {
			const text = content.trim();
			const marker = text.match(MASKED_FENCE);
			return {
				// `value` is docusaurus's required id, and its label fallback
				label: attr(attrs, "label") ?? attr(attrs, "value") ?? "",
				default: isDefault(attrs),
				body: text,
				fence: marker ? fences[Number(marker[1])] : undefined,
			};
		});
		if (items.length === 0) {
			return group;
		}
		const top = Math.max(
			items.findIndex((item) => item.default),
			0,
		);
		const id = `tabs-${groups++}`;
		const strip = items
			.map((item, index) => {
				// `data-title` carries the raw label the way the container's own
				// render does: it is what tab-icon CSS selects on
				const label = escapeHtml(item.label);
				return (
					`<input type="radio" name="${id}" id="${id}-${index}"${index === top ? " checked" : ""}>` +
					`<label data-title="${label}" for="${id}-${index}">${label}</label>`
				);
			})
			.join("");
		const panels = items.map((item, index) => {
			if (item.fence !== undefined) {
				// a lone fence *is* the panel, so its `[title]` goes: the tab
				// above already names the block
				const fence = item.fence.replace(FENCE_INFO, (line) => {
					const bare = line.replace(FENCE_TITLE, "");
					return index === top ? `${bare} active` : bare;
				});
				return fence.trimEnd();
			}
			return (
				`<div class="vp-block${index === top ? " active" : ""}">\n\n` +
				`${item.body}${closeGap(item.body)}</div>`
			);
		});
		// blank-line separated, closing tags included: an html block runs to
		// the next blank line, so a fence hard against a `</div>` is swallowed
		// as raw HTML instead of highlighted
		return (
			`<div class="vp-code-group"><div class="tabs">${strip}</div><div class="blocks">\n\n` +
			`${panels.join("\n\n")}\n\n</div></div>`
		);
	});
}

const FRAME = blockElement("Frame");

// An ATX heading, tolerating the up-to-3-space indent markdown-it accepts. The
// closed form's trailing hashes are a fence, not content.
const ATX_HEADING = /^[ \t]{0,3}(#{1,6})[ \t]+(.+?)(?:[ \t]+#+)?[ \t]*$/gm;

// a code span, which an API page's member headings are written as
const HEADING_CODE_SPAN = /`([^`\n]+)`/g;

/**
 * Rewrites every ATX heading in a frame's body to the HTML heading it would
 * render as, minus the id. A frame quotes content from somewhere else
 * (typically a generated API page, headings and badges included), so those
 * headings are not this page's structure and have no business in its "On this
 * page" list.
 *
 * Writing the element directly is what keeps them out: it never reaches the
 * anchor plugin, so it mints no id, and VitePress's outline drops id-less
 * headings.
 *
 * The heading text is written the same way, because an element's body is raw
 * HTML to markdown-it: a member heading's code span has to become the `<code>`
 * it would have rendered as, or the backticks reach the reader.
 */
function unlistHeadings(body: string): string {
	return body.replace(
		ATX_HEADING,
		(_line, hashes: string, text: string) =>
			`<h${hashes.length}>${text.replace(
				HEADING_CODE_SPAN,
				(_span, code: string) => `<code>${escapeHtml(code)}</code>`,
			)}</h${hashes.length}>`,
	);
}

/**
 * Rewrites `<Frame>` into a bordered block with its label sitting on the top
 * border, linking to `link` when one is given. Without a `label` there is no
 * caption to hang a link on, so the frame renders bare.
 *
 * The body stays markdown: the blank lines around it are what make markdown-it
 * parse it rather than pass the whole element through as raw HTML.
 */
function rewriteFrames(masked: string): string {
	return masked.replace(FRAME, (_frame, attrs: string, body: string) => {
		const label = attr(attrs, "label");
		const link = attr(attrs, "link");
		const caption =
			label === undefined
				? ""
				: `<div class="luaudocs-frame-label">${
						link === undefined
							? escapeHtml(label)
							: `<a href="${escapeHtml(link)}">${escapeHtml(label)}` +
								`<span class="luaudocs-frame-arrow">&#8594;</span></a>`
					}</div>\n`;
		const content = unlistHeadings(body.trim());
		return `<div class="luaudocs-frame">\n${caption}\n${content}${closeGap(content)}</div>`;
	});
}

/**
 * Every rewrite over one page, sharing one masking pass: fences become an
 * opaque marker, which makes "is this tab one code block?" a string test and
 * stops an example that merely *shows* any of this syntax from being rewritten.
 */
export function rewriteMarkup(text: string): string {
	// each rewrite's own precondition, so a page pays only for what it uses
	const tabs = text.includes("<Tabs");
	const frames = text.includes("<Frame");
	const admonitions = /^[ \t]{0,3}:::\w/m.test(text);
	if (!tabs && !frames && !admonitions) {
		return text;
	}
	const fences: string[] = [];
	const masked = splitFences(text)
		.map((part, index) => {
			if (index % 2 === 0) {
				return part;
			}
			// the fence's trailing newline stays *outside* the marker: both
			// rewrites are line-anchored, so folding it in would leave a
			// `:::note` under a code block mid-line and unrewritten
			const newline = part.endsWith("\n") ? "\n" : "";
			const body = newline === "" ? part : part.slice(0, -1);
			return MARK + (fences.push(body) - 1) + MARK + newline;
		})
		.join("");
	let rewritten = masked;
	if (tabs) {
		rewritten = rewriteTabs(rewritten, fences);
	}
	if (frames) {
		rewritten = rewriteFrames(rewritten);
	}
	if (admonitions) {
		rewritten = rewriteAdmonitions(rewritten);
	}
	return rewritten.replace(MASKED_FENCES, (_marker, index: string) => fences[Number(index)]!);
}

/*
 * ------------------------------------------------------------------ page trail
 */

/** One step of a page's trail. A folder with no page of its own has no `link`. */
export interface TrailSegment {
	text: string;
	link?: string;
}

/** The baked trail map, keyed by the docs-relative markdown path VitePress
 * renders each page from. */
export type PageTrails = Record<string, TrailSegment[] | undefined>;

/**
 * Prepends a page's trail, as markdown rather than finished HTML: VitePress
 * bases and dead-link checks a markdown link, and would leave a raw `href` to
 * fend for itself. The blank lines are load bearing, since markdown-it parses
 * an HTML block's contents as markdown only when they stand apart from the tags.
 *
 * Above the title on purpose: VitePress's search indexer drops whatever
 * precedes the first heading, so navigation never enters the index.
 */
export function prependTrail(source: string, trail: TrailSegment[] | undefined): string {
	if (trail === undefined || trail.length === 0) {
		return source;
	}
	const steps = trail
		.map((step) => (step.link === undefined ? step.text : `[${step.text}](${step.link})`))
		.join(" › ");
	return `<div class="luaudocs-trail">\n\n${steps}\n\n</div>\n\n${source}`;
}

/**
 * Both of the above as the one core rule the baked config installs, running
 * over a page's raw source before it is parsed. The trail goes on last, so it
 * lands above the title.
 */
export function installMarkupRule(md: MarkdownIt, trails: PageTrails): void {
	md.core.ruler.before("block", "luaudocs", (state) => {
		// where VitePress puts that path; a page rendered outside its flow
		// carries no key and simply gets no trail
		const page = (state.env as { relativePath?: string } | null)?.relativePath ?? "";
		state.src = prependTrail(rewriteMarkup(state.src), trails[page]);
		return true;
	});
}
