// @generated by luaudocs. Do not edit; regenerated by every build.
//
// The dev search-index cache fix, installed as a vite plugin by the generated
// config.
//
// VitePress imports its dev search index from `/@localSearchIndexroot?v=<n>`,
// and Vite reads a `v=` query as a dependency version stamp, so that URL is
// served `Cache-Control: max-age=31536000,immutable`. But it carries no project
// identity and `<n>` restarts from the same place with every server, so two
// luaudocs sites dev-served on one localhost port share a single year-long
// cache entry and the second answers searches out of the first one's index.
// Renaming the parameter is the whole fix: `rev` is not a version stamp, so
// Vite falls back to `no-cache`, while the counter still busts the module
// registry. Production is unaffected: the built index chunk is content-hashed.
import type { Plugin } from "vite";

export function searchIndexCachePlugin(): Plugin {
	return {
		name: "luaudocs:search-index-cache",
		apply: "serve",
		transform(code, id) {
			// the entry module alone: the per-locale ones are the payloads
			if (id !== "@localSearchIndex" && id !== "/@localSearchIndex") {
				return undefined;
			}
			return code.replace(/(@localSearchIndex\w*\?)v=/g, "$1rev=");
		},
	};
}
