// @generated by luaudocs. Do not edit; regenerated by every build.
//
// Signature link decorations: the emitter writes plain ```luau fences whose
// info string carries `luaudocs-links=[[start,end,"/api/Page#anchor"],...]`
// (offsets into the fence body, end-exclusive). This Shiki transformer reads
// that token off the fence meta and turns each span into a native Shiki
// decoration wrapping the identifier in an <a>. Highlighting, themes, the
// copy button and dual-theme CSS all stay VitePress's own; the emitted
// markdown stays plain Luau for llms-full.txt.
//
// The token cannot reach Shiki as written, so relayLinks/decodeLinks below
// carry it across VitePress's fence renderer; the generated config installs
// both.
import type MarkdownIt from "markdown-it";
import type { ShikiTransformer } from "shiki";

export const LINKS_TOKEN = "luaudocs-links=";

/**
 * The payload carries no whitespace, so it runs to the next space (or the end
 * of the string). Every path below reads and reassembles through this.
 */
function splitToken(
	text: string | undefined,
	token: string,
): { before: string; payload: string; after: string } | undefined {
	const at = text?.indexOf(token) ?? -1;
	if (text === undefined || at === -1) {
		return undefined;
	}
	const before = text.slice(0, at);
	const tail = text.slice(at + token.length);
	const end = tail.indexOf(" ");
	return end === -1
		? { before, payload: tail, after: "" }
		: { before, payload: tail.slice(0, end), after: tail.slice(end) };
}

export function parseLinks(meta: string | undefined): Array<[number, number, string]> | undefined {
	const split = splitToken(meta, LINKS_TOKEN);
	if (split === undefined) {
		return undefined;
	}
	try {
		const parsed: unknown = JSON.parse(split.payload);
		return Array.isArray(parsed) ? (parsed as Array<[number, number, string]>) : undefined;
	} catch {
		return undefined;
	}
}

/**
 * The relay's wire form: base64url carries no brackets, no spaces and no
 * braces, so nothing VitePress does to a fence info string can touch it.
 */
const B64_TOKEN = "luaudocs-links-b64=";

/** Rewrites the `from` token's payload under `to`, leaving the rest of the
 * string byte for byte. Undefined when the token is absent. */
function retoken(
	text: string | undefined,
	from: string,
	to: string,
	recode: (payload: string) => string,
): string | undefined {
	const split = splitToken(text, from);
	return split && split.before + to + recode(split.payload) + split.after;
}

/**
 * Re-encodes the links token before VitePress's fence renderer sees it. Must be
 * installed last, so this wrapper is outermost and runs first.
 *
 * VitePress reads `[title]` in a fence's info string as its code-group title
 * and strips /\[.*\]/ before highlighting, which would swallow
 * `luaudocs-links=[[...]]` whole (greedy, first-`[`-to-last-`]`). Re-encoded,
 * neither that strip nor the whitespace collapse nor `{range}` can reach it.
 */
export function relayLinks(md: MarkdownIt): void {
	const fence = md.renderer.rules.fence!;
	md.renderer.rules.fence = (tokens, idx, opts, env, self) => {
		const token = tokens[idx]!;
		const relayed = retoken(token.info, LINKS_TOKEN, B64_TOKEN, (payload) =>
			Buffer.from(payload).toString("base64url"),
		);
		if (relayed !== undefined) {
			token.info = relayed;
		}
		return fence(tokens, idx, opts, env, self);
	};
}

/** Restores relayLinks()' payload; must run before signatureLinks(). */
export function decodeLinks(): ShikiTransformer {
	return {
		name: "luaudocs:decode-links",
		preprocess() {
			const meta = this.options.meta;
			const decoded = retoken(meta?.__raw, B64_TOKEN, LINKS_TOKEN, (payload) =>
				Buffer.from(payload, "base64url").toString(),
			);
			if (meta !== undefined && decoded !== undefined) {
				meta.__raw = decoded;
			}
		},
	};
}

/**
 * `base` is the site base, and it has to be applied here: these anchors are
 * minted inside Shiki's hast, never as markdown link tokens, and VitePress
 * prefixes the base only in its `link_open` rule. Left unbased, every clickable
 * type in every signature 404s on a project-pages deploy, and because raw HTML
 * never enters `env.links` the dead-link check does not see it either.
 */
export function signatureLinks(base = "/"): ShikiTransformer {
	const prefix = base.replace(/\/$/, "");
	const rooted = (href: string) => (href.startsWith("/") ? `${prefix}${href}` : href);
	return {
		name: "luaudocs:signature-links",
		preprocess(code, options) {
			const links = parseLinks(this.options.meta?.__raw);
			if (!links) {
				return;
			}
			const decorations = (options.decorations ??= []);
			// Shiki THROWS on overlapping or out-of-range decorations; sanitize
			// so a bad span costs one link, never the build
			let cursor = 0;
			for (const entry of links.sort((a, b) => a[0] - b[0])) {
				if (!Array.isArray(entry)) {
					continue;
				}
				const [start, end, href] = entry;
				if (
					typeof start !== "number" ||
					typeof end !== "number" ||
					typeof href !== "string" ||
					start < cursor ||
					end > code.length ||
					start >= end
				) {
					continue;
				}
				cursor = end;
				decorations.push({
					start,
					end,
					tagName: "a",
					properties: { href: rooted(href), class: "sig-link" },
				});
			}
		},
	};
}
