// @generated by luaudocs. Do not edit; regenerated by every build.
//
// Vue's template compiler drops a whitespace-only text node containing a
// newline, where an HTML parser reads a space: a badge row written one badge
// per line renders with its badges touching. So a newline separating inline
// content becomes the space it means, before Vue sees it. A whitespace-
// sensitive element keeps its newlines either way.
import type MarkdownIt from "markdown-it";

const SENSITIVE_TAGS = "pre|script|style|textarea";
const SENSITIVE = new RegExp(`<(?:${SENSITIVE_TAGS})\\b`, "i");
const SENSITIVE_CLOSE = new RegExp(`</(?:${SENSITIVE_TAGS})\\b`, "i");
// VitePress strips its own include markers with a per-line anchored pattern, so
// a marker joined onto the line above stops matching and leaks into the page
const INCLUDE_MARKER = /^[ \t]*<!-- @include-(?:start:|end)/m;

export function whitespacePlugin(md: MarkdownIt): void {
	// markdown-it installs defaults for both rules, so the captures hold
	const softbreak = md.renderer.rules.softbreak!;
	md.renderer.rules.softbreak = (tokens, idx, options, env, self) => {
		// with breaks on a softbreak is a <br>, not whitespace; not our concern
		if (options.breaks) {
			return softbreak(tokens, idx, options, env, self);
		}
		// one opened mid-paragraph is html_inline, which the block rule below
		// never sees: scan back for one still open, where this newline is
		// content rather than layout
		for (let index = idx - 1; index >= 0; index--) {
			if (tokens[index]!.type !== "html_inline") {
				continue;
			}
			const html = tokens[index]!.content;
			if (SENSITIVE_CLOSE.test(html)) {
				break;
			}
			if (SENSITIVE.test(html)) {
				return softbreak(tokens, idx, options, env, self);
			}
		}
		return " ";
	};

	const htmlBlock = md.renderer.rules.html_block!;
	md.renderer.rules.html_block = (tokens, idx, options, env, self) => {
		const token = tokens[idx]!;
		const original = token.content;
		if (!SENSITIVE.test(original) && !INCLUDE_MARKER.test(original)) {
			// the rules VitePress wraps this one in read token.content rather
			// than a return value, so the rewrite goes through the token, then
			// comes back off it
			token.content = original.replace(/[ \t]*\n[ \t]*(?=\S)/g, " ");
		}
		const html = htmlBlock(tokens, idx, options, env, self);
		token.content = original;
		return html;
	};
}
