/**
 * Fills src/generated/: everything the renderer needs from outside the repo, so
 * none of it is checked in. Today that is one file, roblox-names.json: the
 * Roblox name lists the renderer links against, regenerated by `bun install`
 * (via `prepare`) and CI so a fresh clone links against the pinned engine
 * surface without the repo carrying a 35 KB list that goes stale.
 *
 *   bun run generate           # no-op when the file already exists
 *   bun run generate --force   # refetch (after bumping DUMP_COMMIT below)
 *
 * Only this script touches the network: the dump is baked into `dist` at build
 * time, so a luaudocs build never fetches it the way moonwave does.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

// Pinned to a commit so CI's fresh regenerations and a stale local tree read
// the same dump. To bump: take the `roblox` branch's current commit, then
// `--force`.
const DUMP_COMMIT = "473b0da05fa3f3ed397be740d08ffb294ba20b39"; // 0.736.0.7361342
const DUMP_URL = `https://raw.githubusercontent.com/MaximumADHD/Roblox-Client-Tracker/${DUMP_COMMIT}/API-Dump.json`;
const ATTEMPTS = 3;

/** The dump covers Instances and Enums only; datatypes are maintained here. */
const DATATYPES = [
	"Axes",
	"BrickColor",
	"CFrame",
	"CatalogSearchParams",
	"Color3",
	"ColorSequence",
	"ColorSequenceKeypoint",
	"Content",
	"DateTime",
	"DockWidgetPluginGuiInfo",
	"Enum",
	"EnumItem",
	"Enums",
	"Faces",
	"FloatCurveKey",
	"Font",
	"NumberRange",
	"NumberSequence",
	"NumberSequenceKeypoint",
	"OverlapParams",
	"Path2DControlPoint",
	"PathWaypoint",
	"PhysicalProperties",
	"Random",
	"Ray",
	"RaycastParams",
	"RaycastResult",
	"RBXScriptConnection",
	"RBXScriptSignal",
	"Rect",
	"Region3",
	"Region3int16",
	"RotationCurveKey",
	"Secret",
	"SharedTable",
	"TweenInfo",
	"UDim",
	"UDim2",
	"Vector2",
	"Vector2int16",
	"Vector3",
	"Vector3int16",
];

interface DumpType {
	Category: string;
	Name: string;
}

interface DumpMember {
	MemberType: string;
	Name: string;
	Tags?: string[];
	Security?: unknown;
	ReturnType?: DumpType;
}

interface Dump {
	Classes: Array<{ Name: string; Members?: DumpMember[] }>;
	Enums: Array<{ Name: string }>;
}

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(repoRoot, "src", "generated", "roblox-names.json");
const engineOut = join(repoRoot, "extractor", "generated", "engine.luau");

/** The lists engine.luau carries, in emit order, mirroring `EngineLists` in
 * extractor/engine.luau. Both the writer below and the is-it-current check read
 * this one spelling, so a file predating a list cannot pass for a complete one. */
const ENGINE_LISTS = [
	"yieldingMethods",
	"pluginMembers",
	"methodReturns",
	"datatypes",
	"enums",
] as const;

/** The line that opens one list in the emitted file. The writer below and the
 * is-it-current check both go through it, so a change to the emitted shape
 * cannot leave the check probing for a line nothing writes any more. */
function listHeader(name: string): string {
	return `\t${name} = {`;
}

/** `GetCore`, `IsDisabled`: one generic verb plus one word is a name user code
 * plausibly defines too, and a wrong badge costs more than a missing one. */
const GENERIC_NAME = /^(?:Get|Set|Is|Has|Can)[A-Z][a-z0-9]*$/;

/** Plugin members whose names could belong to anything (`Add`, `Undo`,
 * `SetEnabled`) stay out; only unmistakably Studio-flavored names count. */
const PLUGIN_TOKEN = /Plugin|Toolbar|Ribbon|Breakpoint|DockWidget|Studio/;

/** Dump type -> its Luau spelling. `null` is a type inference has no use for:
 * a void return, or a `Tuple`/`Variant`/`Dictionary` too vague to be worth
 * printing next to a property. `Instances` and `Objects` are the dump's names
 * for an array of instances, which Luau spells structurally. */
function luauType(type: DumpType | undefined): string | null {
	if (type === undefined) {
		return null;
	}
	switch (type.Category) {
		case "Primitive":
			return (
				{
					bool: "boolean",
					float: "number",
					int: "number",
					int64: "number",
					double: "number",
					string: "string",
				}[type.Name] ?? null
			);
		case "Enum":
			return `Enum.${type.Name}`;
		case "Class":
			return type.Name;
		case "DataType":
			return type.Name === "Instances" || type.Name === "Objects"
				? "{ Instance }"
				: type.Name;
		default:
			return null;
	}
}

/**
 * Name lists for the extractor's badge detection: an engine method name is
 * usable only when it is unambiguous, meaning no engine member spells the
 * same name with the other behavior.
 */
function engineLists(dump: Dump): { yieldingMethods: string[]; pluginMembers: string[] } {
	const yielding = new Set<string>();
	const nonYielding = new Set<string>();
	const plugin = new Set<string>();
	const open = new Set<string>();
	for (const cls of dump.Classes) {
		for (const member of cls.Members ?? []) {
			if (member.MemberType !== "Function") {
				continue;
			}
			(member.Tags?.includes("Yields") ? yielding : nonYielding).add(member.Name);
			if (member.Security === "PluginSecurity") {
				plugin.add(member.Name);
			} else if (member.Security === "None") {
				open.add(member.Name);
			}
		}
	}
	const yieldingMethods = [...yielding]
		.filter((name) => !nonYielding.has(name) && !GENERIC_NAME.test(name))
		.sort();
	const pluginMembers = [...plugin]
		.filter((name) => !open.has(name) && PLUGIN_TOKEN.test(name))
		.sort();
	return { yieldingMethods, pluginMembers };
}

/**
 * Method name -> return type, for inferring the type of a call on a value the
 * extractor already knows is an Instance. Keyed by name alone, and so limited
 * to names every class spells with one return type: the receiver's class is
 * rarely known, and 1699 of the 2826 names either return void or resolve to a
 * type inference has no use for. The `GENERIC_NAME` caution does not apply: a
 * name only reaches this map after the receiver is established as engine-owned.
 */
function methodReturns(dump: Dump): Array<[string, string]> {
	const byName = new Map<string, Set<string | null>>();
	for (const cls of dump.Classes) {
		for (const member of cls.Members ?? []) {
			if (member.MemberType !== "Function") {
				continue;
			}
			const returns = byName.get(member.Name) ?? new Set<string | null>();
			returns.add(luauType(member.ReturnType));
			byName.set(member.Name, returns);
		}
	}
	return [...byName]
		.flatMap(([name, returns]): Array<[string, string]> => {
			const [only] = [...returns];
			return returns.size === 1 && only != null ? [[name, only]] : [];
		})
		.sort(([a], [b]) => (a < b ? -1 : 1));
}

function luauSet(names: string[]): string {
	return names.map((name) => `\t\t${name} = true,`).join("\n");
}

function luauMap(entries: Array<[string, string]>): string {
	return entries.map(([name, value]) => `\t\t${name} = "${value}",`).join("\n");
}

/**
 * Retried: the file is generated, with no checked-in copy to fall back to, so a
 * transient CDN failure would otherwise break every build in the repo.
 */
async function fetchDump(): Promise<Dump> {
	let last: unknown;
	for (let attempt = 1; attempt <= ATTEMPTS; attempt += 1) {
		try {
			const response = await fetch(DUMP_URL);
			if (!response.ok) {
				throw new Error(`${response.status} ${response.statusText}`);
			}
			return (await response.json()) as Dump;
		} catch (error) {
			last = error;
			if (attempt < ATTEMPTS) {
				const backoff = 500 * 2 ** (attempt - 1);
				console.warn(
					`fetching the API dump failed (attempt ${attempt}/${ATTEMPTS}), retrying in ${backoff}ms`,
				);
				await new Promise((resolve) => setTimeout(resolve, backoff));
			}
		}
	}
	throw new Error(`fetching the API dump failed after ${ATTEMPTS} attempts: ${last}`);
}

/**
 * Whether an engine.luau already on disk carries every list this script writes.
 * One generated before a list was added is worse than none: `extractor/engine`
 * counts it as absent rather than let inference index a missing table, so
 * leaving it would silently drop what the new list knows.
 */
function engineIsCurrent(): boolean {
	if (!existsSync(engineOut)) {
		return false;
	}
	const source = readFileSync(engineOut, "utf8");
	return ENGINE_LISTS.every((name) => source.includes(listHeader(name)));
}

async function generateRobloxNames(force: boolean): Promise<void> {
	if (existsSync(out) && engineIsCurrent() && !force) {
		console.log("roblox-names.json and engine.luau are present; pass --force to refetch");
		return;
	}

	const dump = await fetchDump();
	if (!Array.isArray(dump.Classes) || !Array.isArray(dump.Enums)) {
		throw new Error(
			"the API dump is missing Classes/Enums: refusing to write a truncated name list",
		);
	}

	const names = {
		datatypes: [...DATATYPES].sort(),
		classes: dump.Classes.map((cls) => cls.Name).sort(),
		enums: dump.Enums.map((enumEntry) => enumEntry.Name).sort(),
	};

	mkdirSync(dirname(out), { recursive: true });
	writeFileSync(out, JSON.stringify(names, null, "\t") + "\n");
	console.log(
		`wrote ${out}: ${names.classes.length} classes, ${names.enums.length} enums, ${names.datatypes.length} datatypes`,
	);

	const engine = engineLists(dump);
	const returns = methodReturns(dump);
	const bodies: Record<(typeof ENGINE_LISTS)[number], string> = {
		yieldingMethods: luauSet(engine.yieldingMethods),
		pluginMembers: luauSet(engine.pluginMembers),
		methodReturns: luauMap(returns),
		datatypes: luauSet(names.datatypes),
		enums: luauSet(names.enums),
	};
	const engineSource = [
		"-- Generated by `bun run generate` from the Roblox API dump; never checked",
		"-- in (the prepare hook and CI refresh it). Detection falls back to its",
		"-- built-in convention signals alone when this file is absent, and type",
		"-- inference to the engine-blind half of what it knows.",
		"return {",
		...ENGINE_LISTS.flatMap((name) => [listHeader(name), bodies[name], "\t},"]),
		"}",
		"",
	].join("\n");
	mkdirSync(dirname(engineOut), { recursive: true });
	writeFileSync(engineOut, engineSource);
	console.log(
		`wrote ${engineOut}: ${engine.yieldingMethods.length} yielding methods, ${engine.pluginMembers.length} plugin members, ${returns.length} method returns`,
	);
}

await generateRobloxNames(process.argv.includes("--force"));
