/**
 * DocModel -> PageModel[]: one page per module, its classes as sections.
 * Owns visibility filtering, the listed-type closure, re-export inlining,
 * page-slug disambiguation, and the export edges the nav tree follows. The
 * anchor each heading will be minted with is filled in afterwards by
 * render.ts's mintAnchors, the walk that also renders the page.
 */
import type {
	Badges,
	Class,
	DocModel,
	Fn,
	Inline,
	Member,
	Module,
	Prop,
	Reexport,
	SourceSpan,
	TypeDecl,
} from "./docmodel";
import type { LuauDocsConfig } from "./config";
import { frontmatter } from "./markdown";

/** <docsDir>/api/ on disk, served at /api/. */
export const API_DIR = "api";

/** Site-absolute URL of an API page ("" is the index): the one /api/ prefix. */
export function apiHref(slug: string, anchor?: string): string {
	return `/${API_DIR}/${slug}${anchor ? `#${anchor}` : ""}`;
}

/** A page's key in EmitResult.pages, also its filename under the api/ dir. */
export function apiPageFile(slug: string): string {
	return `${slug}.md`;
}

/** Forward slashes, whatever the platform produced: Node's `relative` spells
 * paths with `\` on Windows (doc-model ids arrive posix already). */
export function toPosix(path: string): string {
	return path.replace(/\\/g, "/");
}

/** The locale is pinned: the default varies by machine/ICU build. */
export function compareTitles(a: string, b: string): number {
	return a.localeCompare(b, "en");
}

/**
 * First line of the files the build writes into user-owned territory (the
 * docs root's index.md and .gitignore). Recognition is the ownership
 * handshake: a file without the line is the user's and is never touched, so
 * deleting the line is how an author takes a generated file over. The prefix
 * is the contract; the rest of the line is free to explain itself.
 */
export const GENERATED_MARK = "# Generated by luaudocs";

/** Whether the build wrote this file: marked on its first line, or on the
 * first line inside its frontmatter (a `#` comment is valid YAML). Through
 * `frontmatter` rather than its own `---` test, so a CRLF checkout of a
 * committed docs dir cannot read a generated page as user-owned. */
export function isGeneratedFile(content: string): boolean {
	return (frontmatter(content) || content).startsWith(GENERATED_MARK);
}

/**
 * The tool owns these pages, so VitePress's edit-link and last-updated
 * affordances would send readers to a file their edits cannot survive in.
 */
export function generatedFrontmatter(title: string, extra: string[] = []): string {
	return [
		"---",
		`title: ${JSON.stringify(title)}`,
		...extra,
		"editLink: false",
		"lastUpdated: false",
		"---",
	].join("\n");
}

/** Page-level only: types render once, ahead of the primary section's members. */
export const TYPES_HEADING = "Types";

/** Provenance of a member inlined from another module's surface. */
export interface ReexportInfo {
	/** module that defines the target; the badge renders "from X" */
	from?: string;
	/** whole-module mount; the badge renders "Module" */
	module?: true;
	/** doc-model id of the definition (the module, for a whole-module mount);
	 * the badge links to it when it lands on a page */
	targetId?: string;
}

export type PageProp = Prop & { reexport?: ReexportInfo };
export type PageFn = Fn & { reexport?: ReexportInfo };
export type PageMember = PageProp | PageFn;
export type PageType = TypeDecl & { reexport?: ReexportInfo };

export interface PageSection {
	/**
	 * Section heading; empty for the primary (module-level) section. Named
	 * (nested/secondary) sections qualify member anchors as `Name.member`.
	 */
	name: string;
	/**
	 * The `anchors` key this section's heading is recorded under; absent for
	 * the primary section, which has no heading. The id rather than the name:
	 * two nested classes on one page can share a short name.
	 */
	id?: string;
	/**
	 * How this section's members are spelled in full (`Color.Linear.fromGamma`;
	 * the module name for the primary section). Composed from `within` +
	 * `name`, never from the heading, which is a nested class's short name.
	 */
	container: string;
	doc?: string;
	tags?: Badges;
	constructors: string[];
	/** every visible member; each renders under the heading its `kind` names */
	members: PageMember[];
	source?: SourceSpan;
}

export interface PageModel {
	slug: string;
	title: string;
	/**
	 * The title qualified with the parent access segment ("Defaults (Flux)"),
	 * present only on a page whose bare title another page claimed first. The
	 * sidebar, search, and browser tab read it; the H1 and URL keep `title`.
	 */
	navTitle?: string;
	moduleId: string;
	/** instance path, root-first: the rojo tree, or the folder layout without one */
	instancePath: string[];
	/** true when this module is one of the project's entry points */
	entry: boolean;
	/**
	 * Module ids of the submodules this page's value exposes publicly (its
	 * re-exports, alias-resolved). This is the access graph the nav tree
	 * follows: `Flux.Motion.Color` mirrors these edges.
	 */
	exports: string[];
	doc?: string;
	tags?: Badges;
	sections: PageSection[];
	types: PageType[];
	source: SourceSpan;
	/** member/type/class id -> the anchor VitePress will mint for its heading */
	anchors: Record<string, string>;
}

/** The label the sidebar, search, and browser tab use; the H1 and URL keep `title`. */
export function displayTitle(page: PageModel): string {
	return page.navTitle ?? page.title;
}

export interface BuildResult {
	pages: PageModel[];
	warnings: string[];
	/** follows aliasOf chains to the module that has a page */
	resolveAlias: (moduleId: string) => string;
}

/**
 * The module's own container: the class carrying the module's name that was not
 * moved there by `@within`. It renders as the page itself, not a section.
 */
export function isPrimaryClass(cls: Class, moduleName: string): boolean {
	return cls.name === moduleName && !cls.within;
}

/**
 * Passthrough modules have no page of their own, so follow the chain (one may
 * alias another) to the module that does.
 */
function aliasResolver(model: DocModel): (moduleId: string) => string {
	const aliases = new Map<string, string>();
	for (const module of model.modules) {
		if (module.aliasOf !== undefined) {
			aliases.set(module.id, module.aliasOf);
		}
	}
	return (moduleId: string) => {
		let current = moduleId;
		const seen = new Set<string>();
		while (aliases.has(current) && !seen.has(current)) {
			seen.add(current);
			current = aliases.get(current)!;
		}
		return current;
	};
}

/** The one visibility rule: private members are dropped unless asked for. */
function isVisible(member: { visibility: string }, includePrivate: boolean): boolean {
	return includePrivate || member.visibility !== "private";
}

function visible<T extends { visibility: string }>(members: T[], includePrivate: boolean): T[] {
	return members.filter((member) => isVisible(member, includePrivate));
}

function sectionHasContent(section: PageSection): boolean {
	return section.members.length > 0 || Boolean(section.doc);
}

function classToSection(cls: Class, primaryName: string, includePrivate: boolean): PageSection {
	const isPrimary = isPrimaryClass(cls, primaryName);
	return {
		name: isPrimary ? "" : cls.name,
		id: isPrimary ? undefined : cls.id,
		container: isPrimary ? primaryName : cls.within ? `${cls.within}.${cls.name}` : cls.name,
		doc: cls.doc,
		tags: cls.tags,
		constructors: cls.constructors,
		members: visible(cls.members, includePrivate),
		source: cls.source,
	};
}

/**
 * The type ids that earn a page entry, over the whole model at once.
 *
 * `export` states the author's intent, but a type the visible surface names
 * needs an entry either way, or signatures mentioning it link nowhere. So both
 * are listed, and the walk closes over what those go on to name.
 *
 * Not per module: `@within` relocates a member onto another module's page while
 * its type refs still name the defining module, so a module-local walk sees
 * neither end of that edge. An invisible declaration is skipped, since nothing
 * renders its refs.
 */
function listedTypeIds(model: DocModel, includePrivate: boolean): Set<string> {
	const decls = new Map<string, TypeDecl>();
	for (const module of model.modules) {
		for (const ty of module.types) {
			decls.set(ty.id, ty);
		}
	}

	const listed = new Set<string>();
	const queue: string[] = [];
	const add = (id: string | undefined) => {
		if (id === undefined || listed.has(id)) {
			return;
		}
		const decl = decls.get(id);
		if (decl === undefined || !isVisible(decl, includePrivate)) {
			return;
		}
		listed.add(id);
		queue.push(id);
	};
	const mention = (segs: Inline | undefined) => {
		for (const seg of segs ?? []) {
			if (typeof seg !== "string") {
				add(seg.id);
			}
		}
	};

	for (const module of model.modules) {
		// a type function has no `export` keyword to state intent with, so it is
		// listed on its own account
		for (const ty of module.types) {
			if (ty.exported || ty.kind === "typefunction") {
				add(ty.id);
			}
		}
		for (const member of [...module.members, ...module.classes.flatMap((cls) => cls.members)]) {
			if (!isVisible(member, includePrivate)) {
				continue;
			}
			if (member.kind === "prop") {
				mention(member.type);
			} else {
				// the signature segs are the whole display after the callee, so
				// they carry every ref the params, returns and generic defaults
				// spell
				mention(member.signature.segs);
			}
		}
	}

	while (queue.length > 0) {
		const decl = decls.get(queue.pop()!)!;
		for (const line of decl.definition ?? []) {
			mention(line);
		}
		for (const field of decl.fields ?? []) {
			mention(field.type);
		}
		// a generic default is a type position like any other
		for (const generic of decl.generics) {
			mention(generic.default);
		}
	}
	return listed;
}

/** What a re-export's `targetId` can name. */
type Definition = { member?: Member; cls?: Class };

/**
 * Every definition a re-export can point at, by doc-model id. A plain lookup:
 * the extractor already decided which definition each re-export names, by
 * walking values rather than matching names.
 */
function definitionsById(model: DocModel): Map<string, Definition> {
	const byId = new Map<string, Definition>();
	for (const module of model.modules) {
		for (const container of [module, ...module.classes]) {
			for (const member of container.members) {
				byId.set(member.id, { member });
			}
		}
		for (const cls of module.classes) {
			byId.set(cls.id, { cls });
		}
	}
	return byId;
}

/**
 * A module's sections: the primary (module-level) section first, then its
 * nested classes. The primary absorbs every class carrying the module's name.
 */
function buildSections(module: Module, includePrivate: boolean): PageSection[] {
	const primary: PageSection = {
		name: "",
		container: module.name,
		constructors: [],
		members: visible(module.members, includePrivate),
	};

	const nested: PageSection[] = [];
	for (const cls of module.classes) {
		const section = classToSection(cls, module.name, includePrivate);
		if (section.name === "") {
			// more than one class can carry the module's name (a root class plus
			// a floating `@class M` on a local): merge, rather than letting the
			// last replace the first's badges and constructors
			primary.doc = primary.doc ?? section.doc;
			primary.tags = primary.tags ?? section.tags;
			primary.constructors.push(...section.constructors);
			primary.members.push(...section.members);
		} else {
			nested.push(section);
		}
	}
	return [primary, ...nested];
}

/**
 * Whole-module mount: the re-export names a module itself. The one place that
 * reads `targetMember` this way.
 */
function isModuleMount(reexport: Reexport): boolean {
	return reexport.targetMember === undefined;
}

/**
 * The property a re-export becomes when its target has nothing member-level to
 * point at. Everything outside `fields` is what makes it synthesized rather
 * than inlined: no visibility or tags of its own.
 */
function synthesizedProp(
	id: string,
	name: string,
	fields: Pick<PageProp, "type" | "doc" | "source" | "reexport">,
): PageProp {
	return {
		id,
		name,
		kind: "prop",
		tags: { custom: [] },
		visibility: "public",
		readonly: false,
		...fields,
	};
}

/** What the re-export inlining phase resolves against, shared across modules. */
interface ReexportContext {
	includePrivate: boolean;
	modulesById: Map<string, Module>;
	definitions: Map<string, Definition>;
}

/**
 * Inlines a module's re-exports into `primary`: a resolved definition becomes
 * the member kind it aliases, a whole-module mount and an undocumented target
 * become props.
 */
function inlineReexports(module: Module, primary: PageSection, ctx: ReexportContext): void {
	for (const reexport of module.reexports) {
		const target = ctx.modulesById.get(reexport.targetModule);
		const id = reexport.id;
		const { member, cls } = (reexport.targetId && ctx.definitions.get(reexport.targetId)) || {};
		// a private definition is not re-exported into a public surface
		if (member && !isVisible(member, ctx.includePrivate)) {
			continue;
		}
		if (member) {
			const reexportInfo = { from: target?.name, targetId: member.id };
			if (member.kind === "prop") {
				primary.members.push({
					...member,
					id,
					name: reexport.name,
					doc: reexport.doc ?? member.doc,
					reexport: reexportInfo,
				});
			} else {
				// re-exported under this module's name, and always as a plain
				// field: a method re-exported as `M.name` is called with a dot
				primary.members.push({
					...member,
					id,
					name: reexport.name,
					kind: "function",
					doc: reexport.doc ?? member.doc,
					signature: {
						...member.signature,
						callee: `${module.name}.${reexport.name}`,
					},
					reexport: reexportInfo,
				});
			}
		} else if (cls) {
			// a nested class of the target module: link to its section
			primary.members.push(
				synthesizedProp(id, reexport.name, {
					// the display is the name and nothing else, one ref segment
					type: [{ text: cls.name, id: cls.id }],
					doc: reexport.doc ?? cls.doc,
					source: cls.source,
					reexport: { from: target?.name, targetId: cls.id },
				}),
			);
		} else {
			// a whole-module mount, or a member the target does not document:
			// neither has anything member-level to point at, so both land on
			// the module page, and only the mount can state a type
			const mount = isModuleMount(reexport);
			primary.members.push(
				synthesizedProp(id, reexport.name, {
					type: mount && target ? [{ text: target.name, id: target.id }] : undefined,
					doc: reexport.doc,
					source: target?.source ?? module.source,
					reexport: mount
						? { module: true, targetId: target?.id }
						: { from: target?.name, targetId: target?.id },
				}),
			);
		}
	}
}

/**
 * The page's slug: display name, disambiguated in module order. The probe
 * skips suffixes another module already claimed under its own name, so `Foo`,
 * `Foo`, `Foo-2` cannot collide.
 */
function claimSlug(
	module: Module,
	usedSlugs: Set<string>,
	warnings: string[],
): { slug: string; collided: boolean } {
	const base = module.name.replace(/[^\w.-]+/g, "-");
	let slug = base;
	for (let n = 2; usedSlugs.has(slug.toLowerCase()); n += 1) {
		slug = `${base}-${n}`;
	}
	usedSlugs.add(slug.toLowerCase());
	const collided = slug !== base;
	if (collided) {
		warnings.push(`page name collision: ${module.name} (${module.id}) becomes /${slug}`);
	}
	return { slug, collided };
}

/**
 * A module a page's value mounts whole is an edge the nav tree follows. Member
 * chains arrive resolved (`M.Remote = Util.Remote` names its end), but a mount
 * can name a passthrough module, which has no page: the edge lands on the
 * module its alias chain ends at.
 */
function linkExports(
	pages: PageModel[],
	modulesById: Map<string, Module>,
	resolveAlias: (moduleId: string) => string,
): void {
	const pageIds = new Set(pages.map((page) => page.moduleId));
	for (const page of pages) {
		const seen = new Set<string>([page.moduleId]);
		for (const reexport of modulesById.get(page.moduleId)?.reexports ?? []) {
			const target = resolveAlias(reexport.targetModule);
			if (isModuleMount(reexport) && pageIds.has(target) && !seen.has(target)) {
				seen.add(target);
				page.exports.push(target);
			}
		}
	}
}

export function buildPages(model: DocModel, config: LuauDocsConfig): BuildResult {
	const includePrivate = config.api.includePrivate;
	const warnings: string[] = [];
	const pages: PageModel[] = [];
	// "index" is reserved: the generated API overview page always claims index.md
	const usedSlugs = new Set<string>(["index"]);
	const normalize = (path: string) => toPosix(path).replace(/^\.\//, "");
	const resolveAlias = aliasResolver(model);
	// a passthrough entry (`return require(script.Impl)`) has no page, so its
	// target must carry the entry flag or the nav loses its root
	const entryIds = new Set(model.project.entryPoints.map(normalize));
	for (const module of model.modules) {
		if (entryIds.has(normalize(module.id))) {
			entryIds.add(normalize(resolveAlias(module.id)));
		}
	}
	// reachability is a property of the whole surface, settled before any page
	// filters its own list
	const listed = listedTypeIds(model, includePrivate);
	const modulesById = new Map(model.modules.map((module) => [module.id, module]));
	const ctx: ReexportContext = {
		includePrivate,
		modulesById,
		definitions: definitionsById(model),
	};

	for (const module of model.modules) {
		if (module.aliasOf !== undefined) {
			continue; // passthrough modules link to their target, no own page
		}

		const sections = buildSections(module, includePrivate);
		const primary = sections[0]!;
		// module order, so the closure's discovery order never reorders the page
		const types = module.types.filter((ty) => listed.has(ty.id));
		inlineReexports(module, primary, ctx);

		const hasContent =
			sections.some(sectionHasContent) || types.length > 0 || Boolean(module.doc);
		if (!hasContent) {
			continue;
		}

		const { slug, collided } = claimSlug(module, usedSlugs, warnings);
		// the loser of a title collision carries its parent access segment, so
		// search results and browser tabs can tell the two pages apart
		const parent = module.instancePath[module.instancePath.length - 2];
		pages.push({
			slug,
			title: module.name,
			navTitle: collided && parent !== undefined ? `${module.name} (${parent})` : undefined,
			moduleId: module.id,
			instancePath: module.instancePath,
			entry: entryIds.has(normalize(module.id)),
			exports: [],
			doc: module.doc,
			tags: primary.tags,
			sections,
			types,
			source: module.source,
			anchors: {},
		});
	}

	linkExports(pages, modulesById, resolveAlias);
	return { pages, warnings, resolveAlias };
}
